# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/error.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/v1/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/error.proto\x12\tcommon.v1\"\x9b\x01\n\x05\x45rror\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12.\n\x06origin\x18\x03 \x01(\x0e\x32\x16.common.v1.FaultOriginR\x06origin\x12\x1c\n\tretryable\x18\x04 \x01(\x08R\tretryable\x12\x16\n\x06\x64\x65tail\x18\x05 \x01(\tR\x06\x64\x65tail*_\n\x0b\x46\x61ultOrigin\x12\x1c\n\x18\x46\x41ULT_ORIGIN_UNSPECIFIED\x10\x00\x12\x17\n\x13\x46\x41ULT_ORIGIN_CALLER\x10\x01\x12\x19\n\x15\x46\x41ULT_ORIGIN_PROVIDER\x10\x02\x42\x62\n\x1e\x63om.cotejs.contracts.common.v1P\x01Z>github.com/rlatkd/cotejs/services/judge/gen/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.cotejs.contracts.common.v1P\001Z>github.com/rlatkd/cotejs/services/judge/gen/common/v1;commonv1'
  _globals['_FAULTORIGIN']._serialized_start=194
  _globals['_FAULTORIGIN']._serialized_end=289
  _globals['_ERROR']._serialized_start=37
  _globals['_ERROR']._serialized_end=192
# @@protoc_insertion_point(module_scope)
