# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: problem/v1/generation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'problem/v1/generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from common.v1 import trace_pb2 as common_dot_v1_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproblem/v1/generation.proto\x12\nproblem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15\x63ommon/v1/trace.proto\"\xf6\x01\n\x11GenerationRequest\x12\x1d\n\nrequest_id\x18\x01 \x01(\x03R\trequestId\x12\x1e\n\ndifficulty\x18\x02 \x01(\tR\ndifficulty\x12\x12\n\x04tags\x18\x03 \x03(\tR\x04tags\x12 \n\x0binstruction\x18\x04 \x01(\tR\x0binstruction\x12=\n\x0crequested_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0brequestedAt\x12-\n\x05trace\x18\x06 \x01(\x0b\x32\x17.common.v1.TraceContextR\x05traceB#\n\x1f\x63om.cotejs.contracts.problem.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'problem.v1.generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.cotejs.contracts.problem.v1P\001'
  _globals['_GENERATIONREQUEST']._serialized_start=100
  _globals['_GENERATIONREQUEST']._serialized_end=346
# @@protoc_insertion_point(module_scope)
