// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/result.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.judge.v1;

@com.google.protobuf.Generated
public interface CaseResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:judge.v1.CaseResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 no = 1 [json_name = "no"];</code>
   * @return The no.
   */
  int getNo();

  /**
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The enum numeric value on the wire for verdict.
   */
  int getVerdictValue();
  /**
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The verdict.
   */
  com.cotejs.contracts.judge.v1.Verdict getVerdict();

  /**
   * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
   * @return The execTimeMs.
   */
  int getExecTimeMs();

  /**
   * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
   * @return The memoryUsedKb.
   */
  int getMemoryUsedKb();
}
