// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/result.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.judge.v1;

/**
 * Protobuf type {@code judge.v1.CaseResult}
 */
@com.google.protobuf.Generated
public final class CaseResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:judge.v1.CaseResult)
    CaseResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CaseResult");
  }
  // Use CaseResult.newBuilder() to construct.
  private CaseResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CaseResult() {
    verdict_ = 0;
    outputSha256_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.judge.v1.CaseResult.class, com.cotejs.contracts.judge.v1.CaseResult.Builder.class);
  }

  public static final int NO_FIELD_NUMBER = 1;
  private int no_ = 0;
  /**
   * <code>uint32 no = 1 [json_name = "no"];</code>
   * @return The no.
   */
  @java.lang.Override
  public int getNo() {
    return no_;
  }

  public static final int VERDICT_FIELD_NUMBER = 2;
  private int verdict_ = 0;
  /**
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The enum numeric value on the wire for verdict.
   */
  @java.lang.Override public int getVerdictValue() {
    return verdict_;
  }
  /**
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The verdict.
   */
  @java.lang.Override public com.cotejs.contracts.judge.v1.Verdict getVerdict() {
    com.cotejs.contracts.judge.v1.Verdict result = com.cotejs.contracts.judge.v1.Verdict.forNumber(verdict_);
    return result == null ? com.cotejs.contracts.judge.v1.Verdict.UNRECOGNIZED : result;
  }

  public static final int EXEC_TIME_MS_FIELD_NUMBER = 3;
  private int execTimeMs_ = 0;
  /**
   * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
   * @return The execTimeMs.
   */
  @java.lang.Override
  public int getExecTimeMs() {
    return execTimeMs_;
  }

  public static final int MEMORY_USED_KB_FIELD_NUMBER = 4;
  private int memoryUsedKb_ = 0;
  /**
   * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
   * @return The memoryUsedKb.
   */
  @java.lang.Override
  public int getMemoryUsedKb() {
    return memoryUsedKb_;
  }

  public static final int OUTPUT_SHA256_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object outputSha256_ = "";
  /**
   * <pre>
   * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
   * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
   * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
   * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
   * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
   * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
   * </pre>
   *
   * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
   * @return The outputSha256.
   */
  @java.lang.Override
  public java.lang.String getOutputSha256() {
    java.lang.Object ref = outputSha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputSha256_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
   * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
   * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
   * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
   * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
   * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
   * </pre>
   *
   * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
   * @return The bytes for outputSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputSha256Bytes() {
    java.lang.Object ref = outputSha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputSha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (no_ != 0) {
      output.writeUInt32(1, no_);
    }
    if (verdict_ != com.cotejs.contracts.judge.v1.Verdict.VERDICT_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, verdict_);
    }
    if (execTimeMs_ != 0) {
      output.writeUInt32(3, execTimeMs_);
    }
    if (memoryUsedKb_ != 0) {
      output.writeUInt32(4, memoryUsedKb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputSha256_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, outputSha256_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (no_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, no_);
    }
    if (verdict_ != com.cotejs.contracts.judge.v1.Verdict.VERDICT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, verdict_);
    }
    if (execTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, execTimeMs_);
    }
    if (memoryUsedKb_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, memoryUsedKb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputSha256_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, outputSha256_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.judge.v1.CaseResult)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.judge.v1.CaseResult other = (com.cotejs.contracts.judge.v1.CaseResult) obj;

    if (getNo()
        != other.getNo()) return false;
    if (verdict_ != other.verdict_) return false;
    if (getExecTimeMs()
        != other.getExecTimeMs()) return false;
    if (getMemoryUsedKb()
        != other.getMemoryUsedKb()) return false;
    if (!getOutputSha256()
        .equals(other.getOutputSha256())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NO_FIELD_NUMBER;
    hash = (53 * hash) + getNo();
    hash = (37 * hash) + VERDICT_FIELD_NUMBER;
    hash = (53 * hash) + verdict_;
    hash = (37 * hash) + EXEC_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getExecTimeMs();
    hash = (37 * hash) + MEMORY_USED_KB_FIELD_NUMBER;
    hash = (53 * hash) + getMemoryUsedKb();
    hash = (37 * hash) + OUTPUT_SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getOutputSha256().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.judge.v1.CaseResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.judge.v1.CaseResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.CaseResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.judge.v1.CaseResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code judge.v1.CaseResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:judge.v1.CaseResult)
      com.cotejs.contracts.judge.v1.CaseResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.judge.v1.CaseResult.class, com.cotejs.contracts.judge.v1.CaseResult.Builder.class);
    }

    // Construct using com.cotejs.contracts.judge.v1.CaseResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      no_ = 0;
      verdict_ = 0;
      execTimeMs_ = 0;
      memoryUsedKb_ = 0;
      outputSha256_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_CaseResult_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.CaseResult getDefaultInstanceForType() {
      return com.cotejs.contracts.judge.v1.CaseResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.CaseResult build() {
      com.cotejs.contracts.judge.v1.CaseResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.CaseResult buildPartial() {
      com.cotejs.contracts.judge.v1.CaseResult result = new com.cotejs.contracts.judge.v1.CaseResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.judge.v1.CaseResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.no_ = no_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.verdict_ = verdict_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.execTimeMs_ = execTimeMs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.memoryUsedKb_ = memoryUsedKb_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.outputSha256_ = outputSha256_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.judge.v1.CaseResult) {
        return mergeFrom((com.cotejs.contracts.judge.v1.CaseResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.judge.v1.CaseResult other) {
      if (other == com.cotejs.contracts.judge.v1.CaseResult.getDefaultInstance()) return this;
      if (other.getNo() != 0) {
        setNo(other.getNo());
      }
      if (other.verdict_ != 0) {
        setVerdictValue(other.getVerdictValue());
      }
      if (other.getExecTimeMs() != 0) {
        setExecTimeMs(other.getExecTimeMs());
      }
      if (other.getMemoryUsedKb() != 0) {
        setMemoryUsedKb(other.getMemoryUsedKb());
      }
      if (!other.getOutputSha256().isEmpty()) {
        outputSha256_ = other.outputSha256_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              no_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              verdict_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              execTimeMs_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              memoryUsedKb_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              outputSha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int no_ ;
    /**
     * <code>uint32 no = 1 [json_name = "no"];</code>
     * @return The no.
     */
    @java.lang.Override
    public int getNo() {
      return no_;
    }
    /**
     * <code>uint32 no = 1 [json_name = "no"];</code>
     * @param value The no to set.
     * @return This builder for chaining.
     */
    public Builder setNo(int value) {

      no_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 no = 1 [json_name = "no"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      no_ = 0;
      onChanged();
      return this;
    }

    private int verdict_ = 0;
    /**
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return The enum numeric value on the wire for verdict.
     */
    @java.lang.Override public int getVerdictValue() {
      return verdict_;
    }
    /**
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @param value The enum numeric value on the wire for verdict to set.
     * @return This builder for chaining.
     */
    public Builder setVerdictValue(int value) {
      verdict_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return The verdict.
     */
    @java.lang.Override
    public com.cotejs.contracts.judge.v1.Verdict getVerdict() {
      com.cotejs.contracts.judge.v1.Verdict result = com.cotejs.contracts.judge.v1.Verdict.forNumber(verdict_);
      return result == null ? com.cotejs.contracts.judge.v1.Verdict.UNRECOGNIZED : result;
    }
    /**
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @param value The verdict to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setVerdict(com.cotejs.contracts.judge.v1.Verdict value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      verdict_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVerdict() {
      bitField0_ = (bitField0_ & ~0x00000002);
      verdict_ = 0;
      onChanged();
      return this;
    }

    private int execTimeMs_ ;
    /**
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @return The execTimeMs.
     */
    @java.lang.Override
    public int getExecTimeMs() {
      return execTimeMs_;
    }
    /**
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @param value The execTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecTimeMs(int value) {

      execTimeMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExecTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      execTimeMs_ = 0;
      onChanged();
      return this;
    }

    private int memoryUsedKb_ ;
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @return The memoryUsedKb.
     */
    @java.lang.Override
    public int getMemoryUsedKb() {
      return memoryUsedKb_;
    }
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @param value The memoryUsedKb to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsedKb(int value) {

      memoryUsedKb_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsedKb() {
      bitField0_ = (bitField0_ & ~0x00000008);
      memoryUsedKb_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object outputSha256_ = "";
    /**
     * <pre>
     * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
     * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
     * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
     * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
     * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
     * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
     * </pre>
     *
     * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
     * @return The outputSha256.
     */
    public java.lang.String getOutputSha256() {
      java.lang.Object ref = outputSha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputSha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
     * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
     * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
     * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
     * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
     * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
     * </pre>
     *
     * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
     * @return The bytes for outputSha256.
     */
    public com.google.protobuf.ByteString
        getOutputSha256Bytes() {
      java.lang.Object ref = outputSha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
     * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
     * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
     * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
     * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
     * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
     * </pre>
     *
     * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
     * @param value The outputSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setOutputSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      outputSha256_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
     * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
     * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
     * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
     * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
     * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
     * </pre>
     *
     * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputSha256() {
      outputSha256_ = getDefaultInstance().getOutputSha256();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 정규화된 실제 출력의 sha256(hex) — 출력이 존재하는 판정(AC·WA)에서만 채워진다.
     * 용도: problem의 합의 검증(M3)이 "풀이 간 합의 vs 초안 기대 일치"를 분리 진단하려면
     * 출력의 동일성 비교가 필요한데, 출력 원문을 결과 토픽에 싣는 것은 과하다(크기·노출).
     * 동일성 판단엔 해시로 충분하다. 정규화 규칙은 judge의 비교 규칙과 동일
     * (CRLF→LF, 각 줄 후행 공백·탭 제거, 말미 빈 줄 제거) — 소비자는 기대 출력에
     * 같은 규칙을 적용해 해시를 만들면 AC 여부와 무관하게 동일성을 판정할 수 있다.
     * </pre>
     *
     * <code>string output_sha256 = 5 [json_name = "outputSha256"];</code>
     * @param value The bytes for outputSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setOutputSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      outputSha256_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:judge.v1.CaseResult)
  }

  // @@protoc_insertion_point(class_scope:judge.v1.CaseResult)
  private static final com.cotejs.contracts.judge.v1.CaseResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.judge.v1.CaseResult();
  }

  public static com.cotejs.contracts.judge.v1.CaseResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CaseResult>
      PARSER = new com.google.protobuf.AbstractParser<CaseResult>() {
    @java.lang.Override
    public CaseResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CaseResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CaseResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.judge.v1.CaseResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

