// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/result.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.judge.v1;

@com.google.protobuf.Generated
public interface JudgeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:judge.v1.JudgeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
   * @return The submissionId.
   */
  long getSubmissionId();

  /**
   * <pre>
   * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
   * </pre>
   *
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The enum numeric value on the wire for verdict.
   */
  int getVerdictValue();
  /**
   * <pre>
   * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
   * </pre>
   *
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The verdict.
   */
  com.cotejs.contracts.judge.v1.Verdict getVerdict();

  /**
   * <pre>
   * 종합 수치 — 케이스 최대값.
   * </pre>
   *
   * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
   * @return The execTimeMs.
   */
  int getExecTimeMs();

  /**
   * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
   * @return The memoryUsedKb.
   */
  int getMemoryUsedKb();

  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  java.util.List<com.cotejs.contracts.judge.v1.CaseResult> 
      getCasesList();
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  com.cotejs.contracts.judge.v1.CaseResult getCases(int index);
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  int getCasesCount();
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  java.util.List<? extends com.cotejs.contracts.judge.v1.CaseResultOrBuilder> 
      getCasesOrBuilderList();
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  com.cotejs.contracts.judge.v1.CaseResultOrBuilder getCasesOrBuilder(
      int index);

  /**
   * <pre>
   * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
   * </pre>
   *
   * <code>string error_message = 6 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
   * </pre>
   *
   * <code>string error_message = 6 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   * @return Whether the judgedAt field is set.
   */
  boolean hasJudgedAt();
  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   * @return The judgedAt.
   */
  com.google.protobuf.Timestamp getJudgedAt();
  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getJudgedAtOrBuilder();
}
