// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/result.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.judge.v1;

/**
 * Protobuf type {@code judge.v1.JudgeResult}
 */
@com.google.protobuf.Generated
public final class JudgeResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:judge.v1.JudgeResult)
    JudgeResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "JudgeResult");
  }
  // Use JudgeResult.newBuilder() to construct.
  private JudgeResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JudgeResult() {
    verdict_ = 0;
    cases_ = java.util.Collections.emptyList();
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_JudgeResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_JudgeResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.judge.v1.JudgeResult.class, com.cotejs.contracts.judge.v1.JudgeResult.Builder.class);
  }

  private int bitField0_;
  public static final int SUBMISSION_ID_FIELD_NUMBER = 1;
  private long submissionId_ = 0L;
  /**
   * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
   * @return The submissionId.
   */
  @java.lang.Override
  public long getSubmissionId() {
    return submissionId_;
  }

  public static final int VERDICT_FIELD_NUMBER = 2;
  private int verdict_ = 0;
  /**
   * <pre>
   * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
   * </pre>
   *
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The enum numeric value on the wire for verdict.
   */
  @java.lang.Override public int getVerdictValue() {
    return verdict_;
  }
  /**
   * <pre>
   * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
   * </pre>
   *
   * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
   * @return The verdict.
   */
  @java.lang.Override public com.cotejs.contracts.judge.v1.Verdict getVerdict() {
    com.cotejs.contracts.judge.v1.Verdict result = com.cotejs.contracts.judge.v1.Verdict.forNumber(verdict_);
    return result == null ? com.cotejs.contracts.judge.v1.Verdict.UNRECOGNIZED : result;
  }

  public static final int EXEC_TIME_MS_FIELD_NUMBER = 3;
  private int execTimeMs_ = 0;
  /**
   * <pre>
   * 종합 수치 — 케이스 최대값.
   * </pre>
   *
   * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
   * @return The execTimeMs.
   */
  @java.lang.Override
  public int getExecTimeMs() {
    return execTimeMs_;
  }

  public static final int MEMORY_USED_KB_FIELD_NUMBER = 4;
  private int memoryUsedKb_ = 0;
  /**
   * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
   * @return The memoryUsedKb.
   */
  @java.lang.Override
  public int getMemoryUsedKb() {
    return memoryUsedKb_;
  }

  public static final int CASES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.cotejs.contracts.judge.v1.CaseResult> cases_;
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  @java.lang.Override
  public java.util.List<com.cotejs.contracts.judge.v1.CaseResult> getCasesList() {
    return cases_;
  }
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cotejs.contracts.judge.v1.CaseResultOrBuilder> 
      getCasesOrBuilderList() {
    return cases_;
  }
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  @java.lang.Override
  public int getCasesCount() {
    return cases_.size();
  }
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  @java.lang.Override
  public com.cotejs.contracts.judge.v1.CaseResult getCases(int index) {
    return cases_.get(index);
  }
  /**
   * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
   */
  @java.lang.Override
  public com.cotejs.contracts.judge.v1.CaseResultOrBuilder getCasesOrBuilder(
      int index) {
    return cases_.get(index);
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
   * </pre>
   *
   * <code>string error_message = 6 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
   * </pre>
   *
   * <code>string error_message = 6 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JUDGED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp judgedAt_;
  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   * @return Whether the judgedAt field is set.
   */
  @java.lang.Override
  public boolean hasJudgedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   * @return The judgedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getJudgedAt() {
    return judgedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : judgedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getJudgedAtOrBuilder() {
    return judgedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : judgedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (submissionId_ != 0L) {
      output.writeInt64(1, submissionId_);
    }
    if (verdict_ != com.cotejs.contracts.judge.v1.Verdict.VERDICT_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, verdict_);
    }
    if (execTimeMs_ != 0) {
      output.writeUInt32(3, execTimeMs_);
    }
    if (memoryUsedKb_ != 0) {
      output.writeUInt32(4, memoryUsedKb_);
    }
    for (int i = 0; i < cases_.size(); i++) {
      output.writeMessage(5, cases_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, errorMessage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getJudgedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (submissionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, submissionId_);
    }
    if (verdict_ != com.cotejs.contracts.judge.v1.Verdict.VERDICT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, verdict_);
    }
    if (execTimeMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, execTimeMs_);
    }
    if (memoryUsedKb_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, memoryUsedKb_);
    }
    for (int i = 0; i < cases_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, cases_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, errorMessage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getJudgedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.judge.v1.JudgeResult)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.judge.v1.JudgeResult other = (com.cotejs.contracts.judge.v1.JudgeResult) obj;

    if (getSubmissionId()
        != other.getSubmissionId()) return false;
    if (verdict_ != other.verdict_) return false;
    if (getExecTimeMs()
        != other.getExecTimeMs()) return false;
    if (getMemoryUsedKb()
        != other.getMemoryUsedKb()) return false;
    if (!getCasesList()
        .equals(other.getCasesList())) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (hasJudgedAt() != other.hasJudgedAt()) return false;
    if (hasJudgedAt()) {
      if (!getJudgedAt()
          .equals(other.getJudgedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBMISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSubmissionId());
    hash = (37 * hash) + VERDICT_FIELD_NUMBER;
    hash = (53 * hash) + verdict_;
    hash = (37 * hash) + EXEC_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + getExecTimeMs();
    hash = (37 * hash) + MEMORY_USED_KB_FIELD_NUMBER;
    hash = (53 * hash) + getMemoryUsedKb();
    if (getCasesCount() > 0) {
      hash = (37 * hash) + CASES_FIELD_NUMBER;
      hash = (53 * hash) + getCasesList().hashCode();
    }
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (hasJudgedAt()) {
      hash = (37 * hash) + JUDGED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getJudgedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.judge.v1.JudgeResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.judge.v1.JudgeResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.JudgeResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.judge.v1.JudgeResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code judge.v1.JudgeResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:judge.v1.JudgeResult)
      com.cotejs.contracts.judge.v1.JudgeResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_JudgeResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_JudgeResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.judge.v1.JudgeResult.class, com.cotejs.contracts.judge.v1.JudgeResult.Builder.class);
    }

    // Construct using com.cotejs.contracts.judge.v1.JudgeResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCasesFieldBuilder();
        internalGetJudgedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      submissionId_ = 0L;
      verdict_ = 0;
      execTimeMs_ = 0;
      memoryUsedKb_ = 0;
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
      } else {
        cases_ = null;
        casesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      errorMessage_ = "";
      judgedAt_ = null;
      if (judgedAtBuilder_ != null) {
        judgedAtBuilder_.dispose();
        judgedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.judge.v1.Result.internal_static_judge_v1_JudgeResult_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.JudgeResult getDefaultInstanceForType() {
      return com.cotejs.contracts.judge.v1.JudgeResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.JudgeResult build() {
      com.cotejs.contracts.judge.v1.JudgeResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.JudgeResult buildPartial() {
      com.cotejs.contracts.judge.v1.JudgeResult result = new com.cotejs.contracts.judge.v1.JudgeResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cotejs.contracts.judge.v1.JudgeResult result) {
      if (casesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          cases_ = java.util.Collections.unmodifiableList(cases_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.cases_ = cases_;
      } else {
        result.cases_ = casesBuilder_.build();
      }
    }

    private void buildPartial0(com.cotejs.contracts.judge.v1.JudgeResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.submissionId_ = submissionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.verdict_ = verdict_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.execTimeMs_ = execTimeMs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.memoryUsedKb_ = memoryUsedKb_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.judgedAt_ = judgedAtBuilder_ == null
            ? judgedAt_
            : judgedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.judge.v1.JudgeResult) {
        return mergeFrom((com.cotejs.contracts.judge.v1.JudgeResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.judge.v1.JudgeResult other) {
      if (other == com.cotejs.contracts.judge.v1.JudgeResult.getDefaultInstance()) return this;
      if (other.getSubmissionId() != 0L) {
        setSubmissionId(other.getSubmissionId());
      }
      if (other.verdict_ != 0) {
        setVerdictValue(other.getVerdictValue());
      }
      if (other.getExecTimeMs() != 0) {
        setExecTimeMs(other.getExecTimeMs());
      }
      if (other.getMemoryUsedKb() != 0) {
        setMemoryUsedKb(other.getMemoryUsedKb());
      }
      if (casesBuilder_ == null) {
        if (!other.cases_.isEmpty()) {
          if (cases_.isEmpty()) {
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCasesIsMutable();
            cases_.addAll(other.cases_);
          }
          onChanged();
        }
      } else {
        if (!other.cases_.isEmpty()) {
          if (casesBuilder_.isEmpty()) {
            casesBuilder_.dispose();
            casesBuilder_ = null;
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000010);
            casesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCasesFieldBuilder() : null;
          } else {
            casesBuilder_.addAllMessages(other.cases_);
          }
        }
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasJudgedAt()) {
        mergeJudgedAt(other.getJudgedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              submissionId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              verdict_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              execTimeMs_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              memoryUsedKb_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.cotejs.contracts.judge.v1.CaseResult m =
                  input.readMessage(
                      com.cotejs.contracts.judge.v1.CaseResult.parser(),
                      extensionRegistry);
              if (casesBuilder_ == null) {
                ensureCasesIsMutable();
                cases_.add(m);
              } else {
                casesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetJudgedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long submissionId_ ;
    /**
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @return The submissionId.
     */
    @java.lang.Override
    public long getSubmissionId() {
      return submissionId_;
    }
    /**
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @param value The submissionId to set.
     * @return This builder for chaining.
     */
    public Builder setSubmissionId(long value) {

      submissionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubmissionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      submissionId_ = 0L;
      onChanged();
      return this;
    }

    private int verdict_ = 0;
    /**
     * <pre>
     * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
     * </pre>
     *
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return The enum numeric value on the wire for verdict.
     */
    @java.lang.Override public int getVerdictValue() {
      return verdict_;
    }
    /**
     * <pre>
     * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
     * </pre>
     *
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @param value The enum numeric value on the wire for verdict to set.
     * @return This builder for chaining.
     */
    public Builder setVerdictValue(int value) {
      verdict_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
     * </pre>
     *
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return The verdict.
     */
    @java.lang.Override
    public com.cotejs.contracts.judge.v1.Verdict getVerdict() {
      com.cotejs.contracts.judge.v1.Verdict result = com.cotejs.contracts.judge.v1.Verdict.forNumber(verdict_);
      return result == null ? com.cotejs.contracts.judge.v1.Verdict.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
     * </pre>
     *
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @param value The verdict to set.
     * @return This builder for chaining.
     */
    public Builder setVerdict(com.cotejs.contracts.judge.v1.Verdict value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      verdict_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 종합 판정 — 첫 실패 케이스의 판정(모두 통과 시 ACCEPTED).
     * </pre>
     *
     * <code>.judge.v1.Verdict verdict = 2 [json_name = "verdict"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVerdict() {
      bitField0_ = (bitField0_ & ~0x00000002);
      verdict_ = 0;
      onChanged();
      return this;
    }

    private int execTimeMs_ ;
    /**
     * <pre>
     * 종합 수치 — 케이스 최대값.
     * </pre>
     *
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @return The execTimeMs.
     */
    @java.lang.Override
    public int getExecTimeMs() {
      return execTimeMs_;
    }
    /**
     * <pre>
     * 종합 수치 — 케이스 최대값.
     * </pre>
     *
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @param value The execTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecTimeMs(int value) {

      execTimeMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 종합 수치 — 케이스 최대값.
     * </pre>
     *
     * <code>uint32 exec_time_ms = 3 [json_name = "execTimeMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExecTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      execTimeMs_ = 0;
      onChanged();
      return this;
    }

    private int memoryUsedKb_ ;
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @return The memoryUsedKb.
     */
    @java.lang.Override
    public int getMemoryUsedKb() {
      return memoryUsedKb_;
    }
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @param value The memoryUsedKb to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsedKb(int value) {

      memoryUsedKb_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 memory_used_kb = 4 [json_name = "memoryUsedKb"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsedKb() {
      bitField0_ = (bitField0_ & ~0x00000008);
      memoryUsedKb_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.cotejs.contracts.judge.v1.CaseResult> cases_ =
      java.util.Collections.emptyList();
    private void ensureCasesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        cases_ = new java.util.ArrayList<com.cotejs.contracts.judge.v1.CaseResult>(cases_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.cotejs.contracts.judge.v1.CaseResult, com.cotejs.contracts.judge.v1.CaseResult.Builder, com.cotejs.contracts.judge.v1.CaseResultOrBuilder> casesBuilder_;

    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public java.util.List<com.cotejs.contracts.judge.v1.CaseResult> getCasesList() {
      if (casesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cases_);
      } else {
        return casesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public int getCasesCount() {
      if (casesBuilder_ == null) {
        return cases_.size();
      } else {
        return casesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public com.cotejs.contracts.judge.v1.CaseResult getCases(int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);
      } else {
        return casesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder setCases(
        int index, com.cotejs.contracts.judge.v1.CaseResult value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.set(index, value);
        onChanged();
      } else {
        casesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder setCases(
        int index, com.cotejs.contracts.judge.v1.CaseResult.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.set(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder addCases(com.cotejs.contracts.judge.v1.CaseResult value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(value);
        onChanged();
      } else {
        casesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder addCases(
        int index, com.cotejs.contracts.judge.v1.CaseResult value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(index, value);
        onChanged();
      } else {
        casesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder addCases(
        com.cotejs.contracts.judge.v1.CaseResult.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder addCases(
        int index, com.cotejs.contracts.judge.v1.CaseResult.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder addAllCases(
        java.lang.Iterable<? extends com.cotejs.contracts.judge.v1.CaseResult> values) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cases_);
        onChanged();
      } else {
        casesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder clearCases() {
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        casesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public Builder removeCases(int index) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.remove(index);
        onChanged();
      } else {
        casesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public com.cotejs.contracts.judge.v1.CaseResult.Builder getCasesBuilder(
        int index) {
      return internalGetCasesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public com.cotejs.contracts.judge.v1.CaseResultOrBuilder getCasesOrBuilder(
        int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);  } else {
        return casesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public java.util.List<? extends com.cotejs.contracts.judge.v1.CaseResultOrBuilder> 
         getCasesOrBuilderList() {
      if (casesBuilder_ != null) {
        return casesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cases_);
      }
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public com.cotejs.contracts.judge.v1.CaseResult.Builder addCasesBuilder() {
      return internalGetCasesFieldBuilder().addBuilder(
          com.cotejs.contracts.judge.v1.CaseResult.getDefaultInstance());
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public com.cotejs.contracts.judge.v1.CaseResult.Builder addCasesBuilder(
        int index) {
      return internalGetCasesFieldBuilder().addBuilder(
          index, com.cotejs.contracts.judge.v1.CaseResult.getDefaultInstance());
    }
    /**
     * <code>repeated .judge.v1.CaseResult cases = 5 [json_name = "cases"];</code>
     */
    public java.util.List<com.cotejs.contracts.judge.v1.CaseResult.Builder> 
         getCasesBuilderList() {
      return internalGetCasesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.cotejs.contracts.judge.v1.CaseResult, com.cotejs.contracts.judge.v1.CaseResult.Builder, com.cotejs.contracts.judge.v1.CaseResultOrBuilder> 
        internalGetCasesFieldBuilder() {
      if (casesBuilder_ == null) {
        casesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.cotejs.contracts.judge.v1.CaseResult, com.cotejs.contracts.judge.v1.CaseResult.Builder, com.cotejs.contracts.judge.v1.CaseResultOrBuilder>(
                cases_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        cases_ = null;
      }
      return casesBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
     * </pre>
     *
     * <code>string error_message = 6 [json_name = "errorMessage"];</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
     * </pre>
     *
     * <code>string error_message = 6 [json_name = "errorMessage"];</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
     * </pre>
     *
     * <code>string error_message = 6 [json_name = "errorMessage"];</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
     * </pre>
     *
     * <code>string error_message = 6 [json_name = "errorMessage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * COMPILE_ERROR·INTERNAL_ERROR 상세(컴파일러 출력 등). 그 외엔 빈 문자열.
     * </pre>
     *
     * <code>string error_message = 6 [json_name = "errorMessage"];</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp judgedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> judgedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     * @return Whether the judgedAt field is set.
     */
    public boolean hasJudgedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     * @return The judgedAt.
     */
    public com.google.protobuf.Timestamp getJudgedAt() {
      if (judgedAtBuilder_ == null) {
        return judgedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : judgedAt_;
      } else {
        return judgedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public Builder setJudgedAt(com.google.protobuf.Timestamp value) {
      if (judgedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        judgedAt_ = value;
      } else {
        judgedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public Builder setJudgedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (judgedAtBuilder_ == null) {
        judgedAt_ = builderForValue.build();
      } else {
        judgedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public Builder mergeJudgedAt(com.google.protobuf.Timestamp value) {
      if (judgedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          judgedAt_ != null &&
          judgedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getJudgedAtBuilder().mergeFrom(value);
        } else {
          judgedAt_ = value;
        }
      } else {
        judgedAtBuilder_.mergeFrom(value);
      }
      if (judgedAt_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public Builder clearJudgedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      judgedAt_ = null;
      if (judgedAtBuilder_ != null) {
        judgedAtBuilder_.dispose();
        judgedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getJudgedAtBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetJudgedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getJudgedAtOrBuilder() {
      if (judgedAtBuilder_ != null) {
        return judgedAtBuilder_.getMessageOrBuilder();
      } else {
        return judgedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : judgedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp judged_at = 7 [json_name = "judgedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetJudgedAtFieldBuilder() {
      if (judgedAtBuilder_ == null) {
        judgedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getJudgedAt(),
                getParentForChildren(),
                isClean());
        judgedAt_ = null;
      }
      return judgedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:judge.v1.JudgeResult)
  }

  // @@protoc_insertion_point(class_scope:judge.v1.JudgeResult)
  private static final com.cotejs.contracts.judge.v1.JudgeResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.judge.v1.JudgeResult();
  }

  public static com.cotejs.contracts.judge.v1.JudgeResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JudgeResult>
      PARSER = new com.google.protobuf.AbstractParser<JudgeResult>() {
    @java.lang.Override
    public JudgeResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JudgeResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JudgeResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.judge.v1.JudgeResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

