// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/submission.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.judge.v1;

@com.google.protobuf.Generated
public interface SubmissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:judge.v1.Submission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 코어 DB(submission.id)의 식별자. 결과 매칭 키.
   * </pre>
   *
   * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
   * @return The submissionId.
   */
  long getSubmissionId();

  /**
   * <code>int64 problem_id = 2 [json_name = "problemId"];</code>
   * @return The problemId.
   */
  long getProblemId();

  /**
   * <pre>
   * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
   * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
   * </pre>
   *
   * <code>string language = 3 [json_name = "language"];</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
   * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
   * </pre>
   *
   * <code>string language = 3 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string source_code = 4 [json_name = "sourceCode"];</code>
   * @return The sourceCode.
   */
  java.lang.String getSourceCode();
  /**
   * <code>string source_code = 4 [json_name = "sourceCode"];</code>
   * @return The bytes for sourceCode.
   */
  com.google.protobuf.ByteString
      getSourceCodeBytes();

  /**
   * <pre>
   * 제한 조건 — DB의 표시용 문자열("1초")이 아닌 수치. api가 발행 시 변환한다.
   * </pre>
   *
   * <code>uint32 time_limit_ms = 5 [json_name = "timeLimitMs"];</code>
   * @return The timeLimitMs.
   */
  int getTimeLimitMs();

  /**
   * <code>uint32 memory_limit_mb = 6 [json_name = "memoryLimitMb"];</code>
   * @return The memoryLimitMb.
   */
  int getMemoryLimitMb();

  /**
   * <pre>
   * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
   * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
   * </pre>
   *
   * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
   * @return The testBundleKey.
   */
  java.lang.String getTestBundleKey();
  /**
   * <pre>
   * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
   * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
   * </pre>
   *
   * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
   * @return The bytes for testBundleKey.
   */
  com.google.protobuf.ByteString
      getTestBundleKeyBytes();

  /**
   * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
   * @return The testBundleSha256.
   */
  java.lang.String getTestBundleSha256();
  /**
   * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
   * @return The bytes for testBundleSha256.
   */
  com.google.protobuf.ByteString
      getTestBundleSha256Bytes();

  /**
   * <pre>
   * UTC 절대시각(ADR-0015). 존 해석의 여지가 없는 타입만 경계에 둔다.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   * @return Whether the submittedAt field is set.
   */
  boolean hasSubmittedAt();
  /**
   * <pre>
   * UTC 절대시각(ADR-0015). 존 해석의 여지가 없는 타입만 경계에 둔다.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   * @return The submittedAt.
   */
  com.google.protobuf.Timestamp getSubmittedAt();
  /**
   * <pre>
   * UTC 절대시각(ADR-0015). 존 해석의 여지가 없는 타입만 경계에 둔다.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder();

  /**
   * <pre>
   * 이 실행 요청이 속한 요청 흐름(ADR-0017). 로그·추적이 서비스를 건너 이어진다.
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 10 [json_name = "trace"];</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <pre>
   * 이 실행 요청이 속한 요청 흐름(ADR-0017). 로그·추적이 서비스를 건너 이어진다.
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 10 [json_name = "trace"];</code>
   * @return The trace.
   */
  com.cotejs.contracts.common.v1.TraceContext getTrace();
  /**
   * <pre>
   * 이 실행 요청이 속한 요청 흐름(ADR-0017). 로그·추적이 서비스를 건너 이어진다.
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 10 [json_name = "trace"];</code>
   */
  com.cotejs.contracts.common.v1.TraceContextOrBuilder getTraceOrBuilder();
}
