// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/submission.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.judge.v1;

@com.google.protobuf.Generated
public final class SubmissionOuterClass extends com.google.protobuf.GeneratedFile {
  private SubmissionOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "SubmissionOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_judge_v1_Submission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_judge_v1_Submission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031judge/v1/submission.proto\022\010judge.v1\032\037g" +
      "oogle/protobuf/timestamp.proto\"\356\002\n\nSubmi" +
      "ssion\022#\n\rsubmission_id\030\001 \001(\003R\014submission" +
      "Id\022\035\n\nproblem_id\030\002 \001(\003R\tproblemId\022\032\n\010lan" +
      "guage\030\003 \001(\tR\010language\022\037\n\013source_code\030\004 \001" +
      "(\tR\nsourceCode\022\"\n\rtime_limit_ms\030\005 \001(\rR\013t" +
      "imeLimitMs\022&\n\017memory_limit_mb\030\006 \001(\rR\rmem" +
      "oryLimitMb\022&\n\017test_bundle_key\030\007 \001(\tR\rtes" +
      "tBundleKey\022,\n\022test_bundle_sha256\030\010 \001(\tR\020" +
      "testBundleSha256\022=\n\014submitted_at\030\t \001(\0132\032" +
      ".google.protobuf.TimestampR\013submittedAtB" +
      "_\n\035com.cotejs.contracts.judge.v1P\001Z<gith" +
      "ub.com/rlatkd/cotejs/services/judge/gen/" +
      "judge/v1;judgev1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_judge_v1_Submission_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_judge_v1_Submission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_judge_v1_Submission_descriptor,
        new java.lang.String[] { "SubmissionId", "ProblemId", "Language", "SourceCode", "TimeLimitMs", "MemoryLimitMb", "TestBundleKey", "TestBundleSha256", "SubmittedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
