// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/submission.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.judge.v1;

/**
 * Protobuf type {@code judge.v1.Submission}
 */
@com.google.protobuf.Generated
public final class Submission extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:judge.v1.Submission)
    SubmissionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Submission");
  }
  // Use Submission.newBuilder() to construct.
  private Submission(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Submission() {
    language_ = "";
    sourceCode_ = "";
    testBundleKey_ = "";
    testBundleSha256_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.judge.v1.SubmissionOuterClass.internal_static_judge_v1_Submission_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.judge.v1.SubmissionOuterClass.internal_static_judge_v1_Submission_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.judge.v1.Submission.class, com.cotejs.contracts.judge.v1.Submission.Builder.class);
  }

  private int bitField0_;
  public static final int SUBMISSION_ID_FIELD_NUMBER = 1;
  private long submissionId_ = 0L;
  /**
   * <pre>
   * 코어 DB(submission.id)의 식별자. 결과 매칭 키.
   * </pre>
   *
   * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
   * @return The submissionId.
   */
  @java.lang.Override
  public long getSubmissionId() {
    return submissionId_;
  }

  public static final int PROBLEM_ID_FIELD_NUMBER = 2;
  private long problemId_ = 0L;
  /**
   * <code>int64 problem_id = 2 [json_name = "problemId"];</code>
   * @return The problemId.
   */
  @java.lang.Override
  public long getProblemId() {
    return problemId_;
  }

  public static final int LANGUAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <pre>
   * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
   * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
   * </pre>
   *
   * <code>string language = 3 [json_name = "language"];</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
   * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
   * </pre>
   *
   * <code>string language = 3 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceCode_ = "";
  /**
   * <code>string source_code = 4 [json_name = "sourceCode"];</code>
   * @return The sourceCode.
   */
  @java.lang.Override
  public java.lang.String getSourceCode() {
    java.lang.Object ref = sourceCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceCode_ = s;
      return s;
    }
  }
  /**
   * <code>string source_code = 4 [json_name = "sourceCode"];</code>
   * @return The bytes for sourceCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceCodeBytes() {
    java.lang.Object ref = sourceCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_LIMIT_MS_FIELD_NUMBER = 5;
  private int timeLimitMs_ = 0;
  /**
   * <pre>
   * 제한 조건 — DB의 표시용 문자열("1초")이 아닌 수치. api가 발행 시 변환한다.
   * </pre>
   *
   * <code>uint32 time_limit_ms = 5 [json_name = "timeLimitMs"];</code>
   * @return The timeLimitMs.
   */
  @java.lang.Override
  public int getTimeLimitMs() {
    return timeLimitMs_;
  }

  public static final int MEMORY_LIMIT_MB_FIELD_NUMBER = 6;
  private int memoryLimitMb_ = 0;
  /**
   * <code>uint32 memory_limit_mb = 6 [json_name = "memoryLimitMb"];</code>
   * @return The memoryLimitMb.
   */
  @java.lang.Override
  public int getMemoryLimitMb() {
    return memoryLimitMb_;
  }

  public static final int TEST_BUNDLE_KEY_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object testBundleKey_ = "";
  /**
   * <pre>
   * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
   * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
   * </pre>
   *
   * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
   * @return The testBundleKey.
   */
  @java.lang.Override
  public java.lang.String getTestBundleKey() {
    java.lang.Object ref = testBundleKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testBundleKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
   * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
   * </pre>
   *
   * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
   * @return The bytes for testBundleKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestBundleKeyBytes() {
    java.lang.Object ref = testBundleKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testBundleKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_BUNDLE_SHA256_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object testBundleSha256_ = "";
  /**
   * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
   * @return The testBundleSha256.
   */
  @java.lang.Override
  public java.lang.String getTestBundleSha256() {
    java.lang.Object ref = testBundleSha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testBundleSha256_ = s;
      return s;
    }
  }
  /**
   * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
   * @return The bytes for testBundleSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestBundleSha256Bytes() {
    java.lang.Object ref = testBundleSha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testBundleSha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBMITTED_AT_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp submittedAt_;
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   * @return Whether the submittedAt field is set.
   */
  @java.lang.Override
  public boolean hasSubmittedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   * @return The submittedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getSubmittedAt() {
    return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder() {
    return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (submissionId_ != 0L) {
      output.writeInt64(1, submissionId_);
    }
    if (problemId_ != 0L) {
      output.writeInt64(2, problemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, sourceCode_);
    }
    if (timeLimitMs_ != 0) {
      output.writeUInt32(5, timeLimitMs_);
    }
    if (memoryLimitMb_ != 0) {
      output.writeUInt32(6, memoryLimitMb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(testBundleKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, testBundleKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(testBundleSha256_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, testBundleSha256_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(9, getSubmittedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (submissionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, submissionId_);
    }
    if (problemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, problemId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, sourceCode_);
    }
    if (timeLimitMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, timeLimitMs_);
    }
    if (memoryLimitMb_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, memoryLimitMb_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(testBundleKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, testBundleKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(testBundleSha256_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, testBundleSha256_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getSubmittedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.judge.v1.Submission)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.judge.v1.Submission other = (com.cotejs.contracts.judge.v1.Submission) obj;

    if (getSubmissionId()
        != other.getSubmissionId()) return false;
    if (getProblemId()
        != other.getProblemId()) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getSourceCode()
        .equals(other.getSourceCode())) return false;
    if (getTimeLimitMs()
        != other.getTimeLimitMs()) return false;
    if (getMemoryLimitMb()
        != other.getMemoryLimitMb()) return false;
    if (!getTestBundleKey()
        .equals(other.getTestBundleKey())) return false;
    if (!getTestBundleSha256()
        .equals(other.getTestBundleSha256())) return false;
    if (hasSubmittedAt() != other.hasSubmittedAt()) return false;
    if (hasSubmittedAt()) {
      if (!getSubmittedAt()
          .equals(other.getSubmittedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBMISSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSubmissionId());
    hash = (37 * hash) + PROBLEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProblemId());
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + SOURCE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceCode().hashCode();
    hash = (37 * hash) + TIME_LIMIT_MS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeLimitMs();
    hash = (37 * hash) + MEMORY_LIMIT_MB_FIELD_NUMBER;
    hash = (53 * hash) + getMemoryLimitMb();
    hash = (37 * hash) + TEST_BUNDLE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getTestBundleKey().hashCode();
    hash = (37 * hash) + TEST_BUNDLE_SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getTestBundleSha256().hashCode();
    if (hasSubmittedAt()) {
      hash = (37 * hash) + SUBMITTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getSubmittedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.judge.v1.Submission parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.judge.v1.Submission parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.judge.v1.Submission parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.judge.v1.Submission prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code judge.v1.Submission}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:judge.v1.Submission)
      com.cotejs.contracts.judge.v1.SubmissionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.judge.v1.SubmissionOuterClass.internal_static_judge_v1_Submission_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.judge.v1.SubmissionOuterClass.internal_static_judge_v1_Submission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.judge.v1.Submission.class, com.cotejs.contracts.judge.v1.Submission.Builder.class);
    }

    // Construct using com.cotejs.contracts.judge.v1.Submission.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSubmittedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      submissionId_ = 0L;
      problemId_ = 0L;
      language_ = "";
      sourceCode_ = "";
      timeLimitMs_ = 0;
      memoryLimitMb_ = 0;
      testBundleKey_ = "";
      testBundleSha256_ = "";
      submittedAt_ = null;
      if (submittedAtBuilder_ != null) {
        submittedAtBuilder_.dispose();
        submittedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.judge.v1.SubmissionOuterClass.internal_static_judge_v1_Submission_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.Submission getDefaultInstanceForType() {
      return com.cotejs.contracts.judge.v1.Submission.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.Submission build() {
      com.cotejs.contracts.judge.v1.Submission result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.judge.v1.Submission buildPartial() {
      com.cotejs.contracts.judge.v1.Submission result = new com.cotejs.contracts.judge.v1.Submission(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.judge.v1.Submission result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.submissionId_ = submissionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.problemId_ = problemId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sourceCode_ = sourceCode_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timeLimitMs_ = timeLimitMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.memoryLimitMb_ = memoryLimitMb_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.testBundleKey_ = testBundleKey_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.testBundleSha256_ = testBundleSha256_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.submittedAt_ = submittedAtBuilder_ == null
            ? submittedAt_
            : submittedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.judge.v1.Submission) {
        return mergeFrom((com.cotejs.contracts.judge.v1.Submission)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.judge.v1.Submission other) {
      if (other == com.cotejs.contracts.judge.v1.Submission.getDefaultInstance()) return this;
      if (other.getSubmissionId() != 0L) {
        setSubmissionId(other.getSubmissionId());
      }
      if (other.getProblemId() != 0L) {
        setProblemId(other.getProblemId());
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSourceCode().isEmpty()) {
        sourceCode_ = other.sourceCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getTimeLimitMs() != 0) {
        setTimeLimitMs(other.getTimeLimitMs());
      }
      if (other.getMemoryLimitMb() != 0) {
        setMemoryLimitMb(other.getMemoryLimitMb());
      }
      if (!other.getTestBundleKey().isEmpty()) {
        testBundleKey_ = other.testBundleKey_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTestBundleSha256().isEmpty()) {
        testBundleSha256_ = other.testBundleSha256_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasSubmittedAt()) {
        mergeSubmittedAt(other.getSubmittedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              submissionId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              problemId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sourceCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              timeLimitMs_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              memoryLimitMb_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              testBundleKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              testBundleSha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetSubmittedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long submissionId_ ;
    /**
     * <pre>
     * 코어 DB(submission.id)의 식별자. 결과 매칭 키.
     * </pre>
     *
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @return The submissionId.
     */
    @java.lang.Override
    public long getSubmissionId() {
      return submissionId_;
    }
    /**
     * <pre>
     * 코어 DB(submission.id)의 식별자. 결과 매칭 키.
     * </pre>
     *
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @param value The submissionId to set.
     * @return This builder for chaining.
     */
    public Builder setSubmissionId(long value) {

      submissionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 코어 DB(submission.id)의 식별자. 결과 매칭 키.
     * </pre>
     *
     * <code>int64 submission_id = 1 [json_name = "submissionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubmissionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      submissionId_ = 0L;
      onChanged();
      return this;
    }

    private long problemId_ ;
    /**
     * <code>int64 problem_id = 2 [json_name = "problemId"];</code>
     * @return The problemId.
     */
    @java.lang.Override
    public long getProblemId() {
      return problemId_;
    }
    /**
     * <code>int64 problem_id = 2 [json_name = "problemId"];</code>
     * @param value The problemId to set.
     * @return This builder for chaining.
     */
    public Builder setProblemId(long value) {

      problemId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 problem_id = 2 [json_name = "problemId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProblemId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      problemId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <pre>
     * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
     * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
     * </pre>
     *
     * <code>string language = 3 [json_name = "language"];</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
     * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
     * </pre>
     *
     * <code>string language = 3 [json_name = "language"];</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
     * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
     * </pre>
     *
     * <code>string language = 3 [json_name = "language"];</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
     * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
     * </pre>
     *
     * <code>string language = 3 [json_name = "language"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 언어 식별자(예: "python"). 첫 슬라이스 언어 범위가 보류 결정이라 enum 대신
     * 문자열 초안 — judge 착수 시 enum 전환 여부 확정.
     * </pre>
     *
     * <code>string language = 3 [json_name = "language"];</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object sourceCode_ = "";
    /**
     * <code>string source_code = 4 [json_name = "sourceCode"];</code>
     * @return The sourceCode.
     */
    public java.lang.String getSourceCode() {
      java.lang.Object ref = sourceCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_code = 4 [json_name = "sourceCode"];</code>
     * @return The bytes for sourceCode.
     */
    public com.google.protobuf.ByteString
        getSourceCodeBytes() {
      java.lang.Object ref = sourceCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_code = 4 [json_name = "sourceCode"];</code>
     * @param value The sourceCode to set.
     * @return This builder for chaining.
     */
    public Builder setSourceCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string source_code = 4 [json_name = "sourceCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceCode() {
      sourceCode_ = getDefaultInstance().getSourceCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string source_code = 4 [json_name = "sourceCode"];</code>
     * @param value The bytes for sourceCode to set.
     * @return This builder for chaining.
     */
    public Builder setSourceCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int timeLimitMs_ ;
    /**
     * <pre>
     * 제한 조건 — DB의 표시용 문자열("1초")이 아닌 수치. api가 발행 시 변환한다.
     * </pre>
     *
     * <code>uint32 time_limit_ms = 5 [json_name = "timeLimitMs"];</code>
     * @return The timeLimitMs.
     */
    @java.lang.Override
    public int getTimeLimitMs() {
      return timeLimitMs_;
    }
    /**
     * <pre>
     * 제한 조건 — DB의 표시용 문자열("1초")이 아닌 수치. api가 발행 시 변환한다.
     * </pre>
     *
     * <code>uint32 time_limit_ms = 5 [json_name = "timeLimitMs"];</code>
     * @param value The timeLimitMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimeLimitMs(int value) {

      timeLimitMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 제한 조건 — DB의 표시용 문자열("1초")이 아닌 수치. api가 발행 시 변환한다.
     * </pre>
     *
     * <code>uint32 time_limit_ms = 5 [json_name = "timeLimitMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeLimitMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timeLimitMs_ = 0;
      onChanged();
      return this;
    }

    private int memoryLimitMb_ ;
    /**
     * <code>uint32 memory_limit_mb = 6 [json_name = "memoryLimitMb"];</code>
     * @return The memoryLimitMb.
     */
    @java.lang.Override
    public int getMemoryLimitMb() {
      return memoryLimitMb_;
    }
    /**
     * <code>uint32 memory_limit_mb = 6 [json_name = "memoryLimitMb"];</code>
     * @param value The memoryLimitMb to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryLimitMb(int value) {

      memoryLimitMb_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 memory_limit_mb = 6 [json_name = "memoryLimitMb"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryLimitMb() {
      bitField0_ = (bitField0_ & ~0x00000020);
      memoryLimitMb_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object testBundleKey_ = "";
    /**
     * <pre>
     * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
     * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
     * </pre>
     *
     * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
     * @return The testBundleKey.
     */
    public java.lang.String getTestBundleKey() {
      java.lang.Object ref = testBundleKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testBundleKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
     * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
     * </pre>
     *
     * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
     * @return The bytes for testBundleKey.
     */
    public com.google.protobuf.ByteString
        getTestBundleKeyBytes() {
      java.lang.Object ref = testBundleKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testBundleKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
     * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
     * </pre>
     *
     * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
     * @param value The testBundleKey to set.
     * @return This builder for chaining.
     */
    public Builder setTestBundleKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      testBundleKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
     * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
     * </pre>
     *
     * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTestBundleKey() {
      testBundleKey_ = getDefaultInstance().getTestBundleKey();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * claim-check(ADR-0009 결정 2): 테스트 데이터는 MinIO 번들, 메시지엔 참조만.
     * judge는 sha256 기준 로컬 캐시 — 해시가 다르면 재다운로드(캐시 무효화 내장).
     * </pre>
     *
     * <code>string test_bundle_key = 7 [json_name = "testBundleKey"];</code>
     * @param value The bytes for testBundleKey to set.
     * @return This builder for chaining.
     */
    public Builder setTestBundleKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      testBundleKey_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object testBundleSha256_ = "";
    /**
     * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
     * @return The testBundleSha256.
     */
    public java.lang.String getTestBundleSha256() {
      java.lang.Object ref = testBundleSha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testBundleSha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
     * @return The bytes for testBundleSha256.
     */
    public com.google.protobuf.ByteString
        getTestBundleSha256Bytes() {
      java.lang.Object ref = testBundleSha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testBundleSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
     * @param value The testBundleSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setTestBundleSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      testBundleSha256_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTestBundleSha256() {
      testBundleSha256_ = getDefaultInstance().getTestBundleSha256();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string test_bundle_sha256 = 8 [json_name = "testBundleSha256"];</code>
     * @param value The bytes for testBundleSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setTestBundleSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      testBundleSha256_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp submittedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> submittedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     * @return Whether the submittedAt field is set.
     */
    public boolean hasSubmittedAt() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     * @return The submittedAt.
     */
    public com.google.protobuf.Timestamp getSubmittedAt() {
      if (submittedAtBuilder_ == null) {
        return submittedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
      } else {
        return submittedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public Builder setSubmittedAt(com.google.protobuf.Timestamp value) {
      if (submittedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        submittedAt_ = value;
      } else {
        submittedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public Builder setSubmittedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (submittedAtBuilder_ == null) {
        submittedAt_ = builderForValue.build();
      } else {
        submittedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public Builder mergeSubmittedAt(com.google.protobuf.Timestamp value) {
      if (submittedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          submittedAt_ != null &&
          submittedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getSubmittedAtBuilder().mergeFrom(value);
        } else {
          submittedAt_ = value;
        }
      } else {
        submittedAtBuilder_.mergeFrom(value);
      }
      if (submittedAt_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public Builder clearSubmittedAt() {
      bitField0_ = (bitField0_ & ~0x00000100);
      submittedAt_ = null;
      if (submittedAtBuilder_ != null) {
        submittedAtBuilder_.dispose();
        submittedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getSubmittedAtBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetSubmittedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSubmittedAtOrBuilder() {
      if (submittedAtBuilder_ != null) {
        return submittedAtBuilder_.getMessageOrBuilder();
      } else {
        return submittedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : submittedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp submitted_at = 9 [json_name = "submittedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetSubmittedAtFieldBuilder() {
      if (submittedAtBuilder_ == null) {
        submittedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSubmittedAt(),
                getParentForChildren(),
                isClean());
        submittedAt_ = null;
      }
      return submittedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:judge.v1.Submission)
  }

  // @@protoc_insertion_point(class_scope:judge.v1.Submission)
  private static final com.cotejs.contracts.judge.v1.Submission DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.judge.v1.Submission();
  }

  public static com.cotejs.contracts.judge.v1.Submission getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Submission>
      PARSER = new com.google.protobuf.AbstractParser<Submission>() {
    @java.lang.Override
    public Submission parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Submission> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Submission> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.judge.v1.Submission getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

