// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: judge/v1/result.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.judge.v1;

/**
 * Protobuf enum {@code judge.v1.Verdict}
 */
@com.google.protobuf.Generated
public enum Verdict
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>VERDICT_UNSPECIFIED = 0;</code>
   */
  VERDICT_UNSPECIFIED(0),
  /**
   * <code>VERDICT_ACCEPTED = 1;</code>
   */
  VERDICT_ACCEPTED(1),
  /**
   * <code>VERDICT_WRONG_ANSWER = 2;</code>
   */
  VERDICT_WRONG_ANSWER(2),
  /**
   * <code>VERDICT_COMPILE_ERROR = 3;</code>
   */
  VERDICT_COMPILE_ERROR(3),
  /**
   * <code>VERDICT_RUNTIME_ERROR = 4;</code>
   */
  VERDICT_RUNTIME_ERROR(4),
  /**
   * <code>VERDICT_TIME_LIMIT_EXCEEDED = 5;</code>
   */
  VERDICT_TIME_LIMIT_EXCEEDED(5),
  /**
   * <code>VERDICT_MEMORY_LIMIT_EXCEEDED = 6;</code>
   */
  VERDICT_MEMORY_LIMIT_EXCEEDED(6),
  /**
   * <pre>
   * 채점 시스템 자체 장애(샌드박스 기동 실패 등) — 유저 귀책이 아니므로 구분.
   * </pre>
   *
   * <code>VERDICT_INTERNAL_ERROR = 7;</code>
   */
  VERDICT_INTERNAL_ERROR(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Verdict");
  }
  /**
   * <code>VERDICT_UNSPECIFIED = 0;</code>
   */
  public static final int VERDICT_UNSPECIFIED_VALUE = 0;
  /**
   * <code>VERDICT_ACCEPTED = 1;</code>
   */
  public static final int VERDICT_ACCEPTED_VALUE = 1;
  /**
   * <code>VERDICT_WRONG_ANSWER = 2;</code>
   */
  public static final int VERDICT_WRONG_ANSWER_VALUE = 2;
  /**
   * <code>VERDICT_COMPILE_ERROR = 3;</code>
   */
  public static final int VERDICT_COMPILE_ERROR_VALUE = 3;
  /**
   * <code>VERDICT_RUNTIME_ERROR = 4;</code>
   */
  public static final int VERDICT_RUNTIME_ERROR_VALUE = 4;
  /**
   * <code>VERDICT_TIME_LIMIT_EXCEEDED = 5;</code>
   */
  public static final int VERDICT_TIME_LIMIT_EXCEEDED_VALUE = 5;
  /**
   * <code>VERDICT_MEMORY_LIMIT_EXCEEDED = 6;</code>
   */
  public static final int VERDICT_MEMORY_LIMIT_EXCEEDED_VALUE = 6;
  /**
   * <pre>
   * 채점 시스템 자체 장애(샌드박스 기동 실패 등) — 유저 귀책이 아니므로 구분.
   * </pre>
   *
   * <code>VERDICT_INTERNAL_ERROR = 7;</code>
   */
  public static final int VERDICT_INTERNAL_ERROR_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Verdict valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Verdict forNumber(int value) {
    switch (value) {
      case 0: return VERDICT_UNSPECIFIED;
      case 1: return VERDICT_ACCEPTED;
      case 2: return VERDICT_WRONG_ANSWER;
      case 3: return VERDICT_COMPILE_ERROR;
      case 4: return VERDICT_RUNTIME_ERROR;
      case 5: return VERDICT_TIME_LIMIT_EXCEEDED;
      case 6: return VERDICT_MEMORY_LIMIT_EXCEEDED;
      case 7: return VERDICT_INTERNAL_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Verdict>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Verdict> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Verdict>() {
          public Verdict findValueByNumber(int number) {
            return Verdict.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cotejs.contracts.judge.v1.Result.getDescriptor().getEnumType(0);
  }

  private static final Verdict[] VALUES = values();

  public static Verdict valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Verdict(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:judge.v1.Verdict)
}

