// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public final class Candidate extends com.google.protobuf.GeneratedFile {
  private Candidate() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Candidate");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problem_v1_IoPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_problem_v1_IoPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problem_v1_ValidationReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_problem_v1_ValidationReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problem_v1_ProblemCandidate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_problem_v1_ProblemCandidate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032problem/v1/candidate.proto\022\nproblem.v1" +
      "\032\037google/protobuf/timestamp.proto\032\025commo" +
      "n/v1/error.proto\032\025common/v1/trace.proto\"" +
      "6\n\006IoPair\022\024\n\005input\030\001 \001(\tR\005input\022\026\n\006outpu" +
      "t\030\002 \001(\tR\006output\"\323\001\n\020ValidationReport\022\'\n\017" +
      "solutions_total\030\001 \001(\rR\016solutionsTotal\022)\n" +
      "\020solutions_agreed\030\002 \001(\rR\017solutionsAgreed" +
      "\022.\n\023brute_force_checked\030\003 \001(\010R\021bruteForc" +
      "eChecked\022%\n\016judge_verified\030\004 \001(\010R\rjudgeV" +
      "erified\022\024\n\005notes\030\005 \001(\tR\005notes\"\261\005\n\020Proble" +
      "mCandidate\022\035\n\nrequest_id\030\001 \001(\003R\trequestI" +
      "d\0223\n\006status\030\002 \001(\0162\033.problem.v1.Candidate" +
      "StatusR\006status\022\024\n\005title\030\003 \001(\tR\005title\022 \n\013" +
      "description\030\004 \001(\tR\013description\022\035\n\ninput_" +
      "spec\030\005 \001(\tR\tinputSpec\022\037\n\013output_spec\030\006 \001" +
      "(\tR\noutputSpec\022\036\n\ndifficulty\030\007 \001(\tR\ndiff" +
      "iculty\022\022\n\004tier\030\010 \001(\tR\004tier\022\022\n\004tags\030\t \003(\t" +
      "R\004tags\022\"\n\rtime_limit_ms\030\n \001(\rR\013timeLimit" +
      "Ms\022&\n\017memory_limit_mb\030\013 \001(\rR\rmemoryLimit" +
      "Mb\022.\n\010examples\030\014 \003(\0132\022.problem.v1.IoPair" +
      "R\010examples\0225\n\014hidden_cases\030\r \003(\0132\022.probl" +
      "em.v1.IoPairR\013hiddenCases\022<\n\nvalidation\030" +
      "\016 \001(\0132\034.problem.v1.ValidationReportR\nval" +
      "idation\022*\n\007failure\030\017 \001(\0132\020.common.v1.Err" +
      "orR\007failure\022=\n\014generated_at\030\020 \001(\0132\032.goog" +
      "le.protobuf.TimestampR\013generatedAt\022-\n\005tr" +
      "ace\030\021 \001(\0132\027.common.v1.TraceContextR\005trac" +
      "e*r\n\017CandidateStatus\022 \n\034CANDIDATE_STATUS" +
      "_UNSPECIFIED\020\000\022\036\n\032CANDIDATE_STATUS_VALID" +
      "ATED\020\001\022\035\n\031CANDIDATE_STATUS_REJECTED\020\002B#\n" +
      "\037com.cotejs.contracts.problem.v1P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.cotejs.contracts.common.v1.ErrorOuterClass.getDescriptor(),
          com.cotejs.contracts.common.v1.Trace.getDescriptor(),
        });
    internal_static_problem_v1_IoPair_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_problem_v1_IoPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_problem_v1_IoPair_descriptor,
        new java.lang.String[] { "Input", "Output", });
    internal_static_problem_v1_ValidationReport_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_problem_v1_ValidationReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_problem_v1_ValidationReport_descriptor,
        new java.lang.String[] { "SolutionsTotal", "SolutionsAgreed", "BruteForceChecked", "JudgeVerified", "Notes", });
    internal_static_problem_v1_ProblemCandidate_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_problem_v1_ProblemCandidate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_problem_v1_ProblemCandidate_descriptor,
        new java.lang.String[] { "RequestId", "Status", "Title", "Description", "InputSpec", "OutputSpec", "Difficulty", "Tier", "Tags", "TimeLimitMs", "MemoryLimitMb", "Examples", "HiddenCases", "Validation", "Failure", "GeneratedAt", "Trace", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.cotejs.contracts.common.v1.ErrorOuterClass.getDescriptor();
    com.cotejs.contracts.common.v1.Trace.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
