// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

/**
 * Protobuf enum {@code problem.v1.CandidateStatus}
 */
@com.google.protobuf.Generated
public enum CandidateStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CANDIDATE_STATUS_UNSPECIFIED = 0;</code>
   */
  CANDIDATE_STATUS_UNSPECIFIED(0),
  /**
   * <pre>
   * 자동 검증 통과 — 검수 큐 대상.
   * </pre>
   *
   * <code>CANDIDATE_STATUS_VALIDATED = 1;</code>
   */
  CANDIDATE_STATUS_VALIDATED(1),
  /**
   * <pre>
   * 자동 검증 반려 — 게시 불가. api는 기록만 한다(생성 성공률 관측용).
   * </pre>
   *
   * <code>CANDIDATE_STATUS_REJECTED = 2;</code>
   */
  CANDIDATE_STATUS_REJECTED(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CandidateStatus");
  }
  /**
   * <code>CANDIDATE_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int CANDIDATE_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 자동 검증 통과 — 검수 큐 대상.
   * </pre>
   *
   * <code>CANDIDATE_STATUS_VALIDATED = 1;</code>
   */
  public static final int CANDIDATE_STATUS_VALIDATED_VALUE = 1;
  /**
   * <pre>
   * 자동 검증 반려 — 게시 불가. api는 기록만 한다(생성 성공률 관측용).
   * </pre>
   *
   * <code>CANDIDATE_STATUS_REJECTED = 2;</code>
   */
  public static final int CANDIDATE_STATUS_REJECTED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CandidateStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CandidateStatus forNumber(int value) {
    switch (value) {
      case 0: return CANDIDATE_STATUS_UNSPECIFIED;
      case 1: return CANDIDATE_STATUS_VALIDATED;
      case 2: return CANDIDATE_STATUS_REJECTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CandidateStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CandidateStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CandidateStatus>() {
          public CandidateStatus findValueByNumber(int number) {
            return CandidateStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cotejs.contracts.problem.v1.Candidate.getDescriptor().getEnumType(0);
  }

  private static final CandidateStatus[] VALUES = values();

  public static CandidateStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CandidateStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:problem.v1.CandidateStatus)
}

