// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/generation.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public interface GenerationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problem.v1.GenerationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * api 코어 DB의 생성 요청 식별자. 후보(candidate) 매칭 키.
   * </pre>
   *
   * <code>int64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <pre>
   * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
   * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
   * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
   * </pre>
   *
   * <code>string difficulty = 2 [json_name = "difficulty"];</code>
   * @return The difficulty.
   */
  java.lang.String getDifficulty();
  /**
   * <pre>
   * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
   * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
   * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
   * </pre>
   *
   * <code>string difficulty = 2 [json_name = "difficulty"];</code>
   * @return The bytes for difficulty.
   */
  com.google.protobuf.ByteString
      getDifficultyBytes();

  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
   * </pre>
   *
   * <code>string instruction = 4 [json_name = "instruction"];</code>
   * @return The instruction.
   */
  java.lang.String getInstruction();
  /**
   * <pre>
   * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
   * </pre>
   *
   * <code>string instruction = 4 [json_name = "instruction"];</code>
   * @return The bytes for instruction.
   */
  com.google.protobuf.ByteString
      getInstructionBytes();

  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   * @return Whether the requestedAt field is set.
   */
  boolean hasRequestedAt();
  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   * @return The requestedAt.
   */
  com.google.protobuf.Timestamp getRequestedAt();
  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder();

  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   * @return The trace.
   */
  com.cotejs.contracts.common.v1.TraceContext getTrace();
  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   */
  com.cotejs.contracts.common.v1.TraceContextOrBuilder getTraceOrBuilder();
}
