// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/generation.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public final class Generation extends com.google.protobuf.GeneratedFile {
  private Generation() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Generation");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_problem_v1_GenerationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_problem_v1_GenerationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033problem/v1/generation.proto\022\nproblem.v" +
      "1\032\037google/protobuf/timestamp.proto\032\025comm" +
      "on/v1/trace.proto\"\366\001\n\021GenerationRequest\022" +
      "\035\n\nrequest_id\030\001 \001(\003R\trequestId\022\036\n\ndiffic" +
      "ulty\030\002 \001(\tR\ndifficulty\022\022\n\004tags\030\003 \003(\tR\004ta" +
      "gs\022 \n\013instruction\030\004 \001(\tR\013instruction\022=\n\014" +
      "requested_at\030\005 \001(\0132\032.google.protobuf.Tim" +
      "estampR\013requestedAt\022-\n\005trace\030\006 \001(\0132\027.com" +
      "mon.v1.TraceContextR\005traceB#\n\037com.cotejs" +
      ".contracts.problem.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.cotejs.contracts.common.v1.Trace.getDescriptor(),
        });
    internal_static_problem_v1_GenerationRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_problem_v1_GenerationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_problem_v1_GenerationRequest_descriptor,
        new java.lang.String[] { "RequestId", "Difficulty", "Tags", "Instruction", "RequestedAt", "Trace", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.cotejs.contracts.common.v1.Trace.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
