// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/generation.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

/**
 * Protobuf type {@code problem.v1.GenerationRequest}
 */
@com.google.protobuf.Generated
public final class GenerationRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:problem.v1.GenerationRequest)
    GenerationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GenerationRequest");
  }
  // Use GenerationRequest.newBuilder() to construct.
  private GenerationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GenerationRequest() {
    difficulty_ = "";
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    instruction_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.problem.v1.GenerationRequest.class, com.cotejs.contracts.problem.v1.GenerationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private long requestId_ = 0L;
  /**
   * <pre>
   * api 코어 DB의 생성 요청 식별자. 후보(candidate) 매칭 키.
   * </pre>
   *
   * <code>int64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  @java.lang.Override
  public long getRequestId() {
    return requestId_;
  }

  public static final int DIFFICULTY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object difficulty_ = "";
  /**
   * <pre>
   * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
   * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
   * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
   * </pre>
   *
   * <code>string difficulty = 2 [json_name = "difficulty"];</code>
   * @return The difficulty.
   */
  @java.lang.Override
  public java.lang.String getDifficulty() {
    java.lang.Object ref = difficulty_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      difficulty_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
   * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
   * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
   * </pre>
   *
   * <code>string difficulty = 2 [json_name = "difficulty"];</code>
   * @return The bytes for difficulty.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDifficultyBytes() {
    java.lang.Object ref = difficulty_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      difficulty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * 예: ["BFS", "그래프 탐색"]
   * </pre>
   *
   * <code>repeated string tags = 3 [json_name = "tags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int INSTRUCTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instruction_ = "";
  /**
   * <pre>
   * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
   * </pre>
   *
   * <code>string instruction = 4 [json_name = "instruction"];</code>
   * @return The instruction.
   */
  @java.lang.Override
  public java.lang.String getInstruction() {
    java.lang.Object ref = instruction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instruction_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
   * </pre>
   *
   * <code>string instruction = 4 [json_name = "instruction"];</code>
   * @return The bytes for instruction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstructionBytes() {
    java.lang.Object ref = instruction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instruction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp requestedAt_;
  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   * @return Whether the requestedAt field is set.
   */
  @java.lang.Override
  public boolean hasRequestedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   * @return The requestedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRequestedAt() {
    return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
  }
  /**
   * <pre>
   * UTC 절대시각(ADR-0015)
   * </pre>
   *
   * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder() {
    return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
  }

  public static final int TRACE_FIELD_NUMBER = 6;
  private com.cotejs.contracts.common.v1.TraceContext trace_;
  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.cotejs.contracts.common.v1.TraceContext getTrace() {
    return trace_ == null ? com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance() : trace_;
  }
  /**
   * <pre>
   * 요청 흐름(ADR-0017)
   * </pre>
   *
   * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
   */
  @java.lang.Override
  public com.cotejs.contracts.common.v1.TraceContextOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance() : trace_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestId_ != 0L) {
      output.writeInt64(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(difficulty_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, difficulty_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tags_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instruction_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, instruction_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getRequestedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getTrace());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (requestId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, requestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(difficulty_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, difficulty_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instruction_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, instruction_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRequestedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTrace());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.problem.v1.GenerationRequest)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.problem.v1.GenerationRequest other = (com.cotejs.contracts.problem.v1.GenerationRequest) obj;

    if (getRequestId()
        != other.getRequestId()) return false;
    if (!getDifficulty()
        .equals(other.getDifficulty())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getInstruction()
        .equals(other.getInstruction())) return false;
    if (hasRequestedAt() != other.hasRequestedAt()) return false;
    if (hasRequestedAt()) {
      if (!getRequestedAt()
          .equals(other.getRequestedAt())) return false;
    }
    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestId());
    hash = (37 * hash) + DIFFICULTY_FIELD_NUMBER;
    hash = (53 * hash) + getDifficulty().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
    hash = (53 * hash) + getInstruction().hashCode();
    if (hasRequestedAt()) {
      hash = (37 * hash) + REQUESTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedAt().hashCode();
    }
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.problem.v1.GenerationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.problem.v1.GenerationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.problem.v1.GenerationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.problem.v1.GenerationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code problem.v1.GenerationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:problem.v1.GenerationRequest)
      com.cotejs.contracts.problem.v1.GenerationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.problem.v1.GenerationRequest.class, com.cotejs.contracts.problem.v1.GenerationRequest.Builder.class);
    }

    // Construct using com.cotejs.contracts.problem.v1.GenerationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRequestedAtFieldBuilder();
        internalGetTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = 0L;
      difficulty_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      instruction_ = "";
      requestedAt_ = null;
      if (requestedAtBuilder_ != null) {
        requestedAtBuilder_.dispose();
        requestedAtBuilder_ = null;
      }
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.problem.v1.Generation.internal_static_problem_v1_GenerationRequest_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.GenerationRequest getDefaultInstanceForType() {
      return com.cotejs.contracts.problem.v1.GenerationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.GenerationRequest build() {
      com.cotejs.contracts.problem.v1.GenerationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.GenerationRequest buildPartial() {
      com.cotejs.contracts.problem.v1.GenerationRequest result = new com.cotejs.contracts.problem.v1.GenerationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.problem.v1.GenerationRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.difficulty_ = difficulty_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.instruction_ = instruction_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.requestedAt_ = requestedAtBuilder_ == null
            ? requestedAt_
            : requestedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.problem.v1.GenerationRequest) {
        return mergeFrom((com.cotejs.contracts.problem.v1.GenerationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.problem.v1.GenerationRequest other) {
      if (other == com.cotejs.contracts.problem.v1.GenerationRequest.getDefaultInstance()) return this;
      if (other.getRequestId() != 0L) {
        setRequestId(other.getRequestId());
      }
      if (!other.getDifficulty().isEmpty()) {
        difficulty_ = other.difficulty_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000004;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getInstruction().isEmpty()) {
        instruction_ = other.instruction_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasRequestedAt()) {
        mergeRequestedAt(other.getRequestedAt());
      }
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              requestId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              difficulty_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ensureTagsIsMutable();
              tags_.add(input.readStringRequireUtf8());
              break;
            } // case 26
            case 34: {
              instruction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetRequestedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long requestId_ ;
    /**
     * <pre>
     * api 코어 DB의 생성 요청 식별자. 후보(candidate) 매칭 키.
     * </pre>
     *
     * <code>int64 request_id = 1 [json_name = "requestId"];</code>
     * @return The requestId.
     */
    @java.lang.Override
    public long getRequestId() {
      return requestId_;
    }
    /**
     * <pre>
     * api 코어 DB의 생성 요청 식별자. 후보(candidate) 매칭 키.
     * </pre>
     *
     * <code>int64 request_id = 1 [json_name = "requestId"];</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(long value) {

      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * api 코어 DB의 생성 요청 식별자. 후보(candidate) 매칭 키.
     * </pre>
     *
     * <code>int64 request_id = 1 [json_name = "requestId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object difficulty_ = "";
    /**
     * <pre>
     * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
     * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
     * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
     * </pre>
     *
     * <code>string difficulty = 2 [json_name = "difficulty"];</code>
     * @return The difficulty.
     */
    public java.lang.String getDifficulty() {
      java.lang.Object ref = difficulty_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        difficulty_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
     * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
     * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
     * </pre>
     *
     * <code>string difficulty = 2 [json_name = "difficulty"];</code>
     * @return The bytes for difficulty.
     */
    public com.google.protobuf.ByteString
        getDifficultyBytes() {
      java.lang.Object ref = difficulty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        difficulty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
     * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
     * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
     * </pre>
     *
     * <code>string difficulty = 2 [json_name = "difficulty"];</code>
     * @param value The difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficulty(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      difficulty_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
     * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
     * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
     * </pre>
     *
     * <code>string difficulty = 2 [json_name = "difficulty"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDifficulty() {
      difficulty_ = getDefaultInstance().getDifficulty();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 생성 파라미터 — 값 어휘(티어 명칭 등)는 api가 진실원이고 여기선 운반만 한다.
     * 채점 지식(judge 레지스트리)과 서빙 지식(api)을 가르는 기존 원칙과 동일하게,
     * 생성 지식의 어휘 검증은 problem 파이프라인 안에서 한다.
     * </pre>
     *
     * <code>string difficulty = 2 [json_name = "difficulty"];</code>
     * @param value The bytes for difficulty to set.
     * @return This builder for chaining.
     */
    public Builder setDifficultyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      difficulty_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 예: ["BFS", "그래프 탐색"]
     * </pre>
     *
     * <code>repeated string tags = 3 [json_name = "tags"];</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object instruction_ = "";
    /**
     * <pre>
     * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
     * </pre>
     *
     * <code>string instruction = 4 [json_name = "instruction"];</code>
     * @return The instruction.
     */
    public java.lang.String getInstruction() {
      java.lang.Object ref = instruction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instruction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
     * </pre>
     *
     * <code>string instruction = 4 [json_name = "instruction"];</code>
     * @return The bytes for instruction.
     */
    public com.google.protobuf.ByteString
        getInstructionBytes() {
      java.lang.Object ref = instruction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instruction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
     * </pre>
     *
     * <code>string instruction = 4 [json_name = "instruction"];</code>
     * @param value The instruction to set.
     * @return This builder for chaining.
     */
    public Builder setInstruction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instruction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
     * </pre>
     *
     * <code>string instruction = 4 [json_name = "instruction"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInstruction() {
      instruction_ = getDefaultInstance().getInstruction();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 관리자가 덧붙이는 자유 서술 지시(선택). 예: "격자 탐색 소재로".
     * </pre>
     *
     * <code>string instruction = 4 [json_name = "instruction"];</code>
     * @param value The bytes for instruction to set.
     * @return This builder for chaining.
     */
    public Builder setInstructionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instruction_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp requestedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> requestedAtBuilder_;
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     * @return Whether the requestedAt field is set.
     */
    public boolean hasRequestedAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     * @return The requestedAt.
     */
    public com.google.protobuf.Timestamp getRequestedAt() {
      if (requestedAtBuilder_ == null) {
        return requestedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
      } else {
        return requestedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public Builder setRequestedAt(com.google.protobuf.Timestamp value) {
      if (requestedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestedAt_ = value;
      } else {
        requestedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public Builder setRequestedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (requestedAtBuilder_ == null) {
        requestedAt_ = builderForValue.build();
      } else {
        requestedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public Builder mergeRequestedAt(com.google.protobuf.Timestamp value) {
      if (requestedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          requestedAt_ != null &&
          requestedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRequestedAtBuilder().mergeFrom(value);
        } else {
          requestedAt_ = value;
        }
      } else {
        requestedAtBuilder_.mergeFrom(value);
      }
      if (requestedAt_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public Builder clearRequestedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      requestedAt_ = null;
      if (requestedAtBuilder_ != null) {
        requestedAtBuilder_.dispose();
        requestedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getRequestedAtBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetRequestedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRequestedAtOrBuilder() {
      if (requestedAtBuilder_ != null) {
        return requestedAtBuilder_.getMessageOrBuilder();
      } else {
        return requestedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : requestedAt_;
      }
    }
    /**
     * <pre>
     * UTC 절대시각(ADR-0015)
     * </pre>
     *
     * <code>.google.protobuf.Timestamp requested_at = 5 [json_name = "requestedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetRequestedAtFieldBuilder() {
      if (requestedAtBuilder_ == null) {
        requestedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRequestedAt(),
                getParentForChildren(),
                isClean());
        requestedAt_ = null;
      }
      return requestedAtBuilder_;
    }

    private com.cotejs.contracts.common.v1.TraceContext trace_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cotejs.contracts.common.v1.TraceContext, com.cotejs.contracts.common.v1.TraceContext.Builder, com.cotejs.contracts.common.v1.TraceContextOrBuilder> traceBuilder_;
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     * @return The trace.
     */
    public com.cotejs.contracts.common.v1.TraceContext getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public Builder setTrace(com.cotejs.contracts.common.v1.TraceContext value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public Builder setTrace(
        com.cotejs.contracts.common.v1.TraceContext.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public Builder mergeTrace(com.cotejs.contracts.common.v1.TraceContext value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          trace_ != null &&
          trace_ != com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000020);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public com.cotejs.contracts.common.v1.TraceContext.Builder getTraceBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetTraceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    public com.cotejs.contracts.common.v1.TraceContextOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance() : trace_;
      }
    }
    /**
     * <pre>
     * 요청 흐름(ADR-0017)
     * </pre>
     *
     * <code>.common.v1.TraceContext trace = 6 [json_name = "trace"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cotejs.contracts.common.v1.TraceContext, com.cotejs.contracts.common.v1.TraceContext.Builder, com.cotejs.contracts.common.v1.TraceContextOrBuilder> 
        internalGetTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cotejs.contracts.common.v1.TraceContext, com.cotejs.contracts.common.v1.TraceContext.Builder, com.cotejs.contracts.common.v1.TraceContextOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:problem.v1.GenerationRequest)
  }

  // @@protoc_insertion_point(class_scope:problem.v1.GenerationRequest)
  private static final com.cotejs.contracts.problem.v1.GenerationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.problem.v1.GenerationRequest();
  }

  public static com.cotejs.contracts.problem.v1.GenerationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerationRequest>
      PARSER = new com.google.protobuf.AbstractParser<GenerationRequest>() {
    @java.lang.Override
    public GenerationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GenerationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.problem.v1.GenerationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

