// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public interface IoPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problem.v1.IoPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1 [json_name = "input"];</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();

  /**
   * <code>string output = 2 [json_name = "output"];</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 2 [json_name = "output"];</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
