// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public interface ProblemCandidateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problem.v1.ProblemCandidate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * GenerationRequest.request_id 매칭 키.
   * </pre>
   *
   * <code>int64 request_id = 1 [json_name = "requestId"];</code>
   * @return The requestId.
   */
  long getRequestId();

  /**
   * <code>.problem.v1.CandidateStatus status = 2 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.problem.v1.CandidateStatus status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  com.cotejs.contracts.problem.v1.CandidateStatus getStatus();

  /**
   * <pre>
   * ---- 문제 본문 (api problem 스키마와 어휘를 맞춘다) ----
   * </pre>
   *
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * ---- 문제 본문 (api problem 스키마와 어휘를 맞춘다) ----
   * </pre>
   *
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 지문(markdown)
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * 지문(markdown)
   * </pre>
   *
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * 입력 형식 서술
   * </pre>
   *
   * <code>string input_spec = 5 [json_name = "inputSpec"];</code>
   * @return The inputSpec.
   */
  java.lang.String getInputSpec();
  /**
   * <pre>
   * 입력 형식 서술
   * </pre>
   *
   * <code>string input_spec = 5 [json_name = "inputSpec"];</code>
   * @return The bytes for inputSpec.
   */
  com.google.protobuf.ByteString
      getInputSpecBytes();

  /**
   * <pre>
   * 출력 형식 서술
   * </pre>
   *
   * <code>string output_spec = 6 [json_name = "outputSpec"];</code>
   * @return The outputSpec.
   */
  java.lang.String getOutputSpec();
  /**
   * <pre>
   * 출력 형식 서술
   * </pre>
   *
   * <code>string output_spec = 6 [json_name = "outputSpec"];</code>
   * @return The bytes for outputSpec.
   */
  com.google.protobuf.ByteString
      getOutputSpecBytes();

  /**
   * <code>string difficulty = 7 [json_name = "difficulty"];</code>
   * @return The difficulty.
   */
  java.lang.String getDifficulty();
  /**
   * <code>string difficulty = 7 [json_name = "difficulty"];</code>
   * @return The bytes for difficulty.
   */
  com.google.protobuf.ByteString
      getDifficultyBytes();

  /**
   * <code>string tier = 8 [json_name = "tier"];</code>
   * @return The tier.
   */
  java.lang.String getTier();
  /**
   * <code>string tier = 8 [json_name = "tier"];</code>
   * @return The bytes for tier.
   */
  com.google.protobuf.ByteString
      getTierBytes();

  /**
   * <code>repeated string tags = 9 [json_name = "tags"];</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 9 [json_name = "tags"];</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 9 [json_name = "tags"];</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 9 [json_name = "tags"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 제한 — 수치 규약(judge 계약과 동일). 시간 제한은 의도 풀이 실측의 여유 배수로 산정한다
   * (learning-notes '오판정': 경계선 TLE 완화 관행).
   * </pre>
   *
   * <code>uint32 time_limit_ms = 10 [json_name = "timeLimitMs"];</code>
   * @return The timeLimitMs.
   */
  int getTimeLimitMs();

  /**
   * <code>uint32 memory_limit_mb = 11 [json_name = "memoryLimitMb"];</code>
   * @return The memoryLimitMb.
   */
  int getMemoryLimitMb();

  /**
   * <pre>
   * 공개 예제(run 모드에서 사용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair examples = 12 [json_name = "examples"];</code>
   */
  java.util.List<com.cotejs.contracts.problem.v1.IoPair> 
      getExamplesList();
  /**
   * <pre>
   * 공개 예제(run 모드에서 사용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair examples = 12 [json_name = "examples"];</code>
   */
  com.cotejs.contracts.problem.v1.IoPair getExamples(int index);
  /**
   * <pre>
   * 공개 예제(run 모드에서 사용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair examples = 12 [json_name = "examples"];</code>
   */
  int getExamplesCount();
  /**
   * <pre>
   * 공개 예제(run 모드에서 사용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair examples = 12 [json_name = "examples"];</code>
   */
  java.util.List<? extends com.cotejs.contracts.problem.v1.IoPairOrBuilder> 
      getExamplesOrBuilderList();
  /**
   * <pre>
   * 공개 예제(run 모드에서 사용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair examples = 12 [json_name = "examples"];</code>
   */
  com.cotejs.contracts.problem.v1.IoPairOrBuilder getExamplesOrBuilder(
      int index);

  /**
   * <pre>
   * 히든 케이스(submit 채점용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair hidden_cases = 13 [json_name = "hiddenCases"];</code>
   */
  java.util.List<com.cotejs.contracts.problem.v1.IoPair> 
      getHiddenCasesList();
  /**
   * <pre>
   * 히든 케이스(submit 채점용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair hidden_cases = 13 [json_name = "hiddenCases"];</code>
   */
  com.cotejs.contracts.problem.v1.IoPair getHiddenCases(int index);
  /**
   * <pre>
   * 히든 케이스(submit 채점용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair hidden_cases = 13 [json_name = "hiddenCases"];</code>
   */
  int getHiddenCasesCount();
  /**
   * <pre>
   * 히든 케이스(submit 채점용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair hidden_cases = 13 [json_name = "hiddenCases"];</code>
   */
  java.util.List<? extends com.cotejs.contracts.problem.v1.IoPairOrBuilder> 
      getHiddenCasesOrBuilderList();
  /**
   * <pre>
   * 히든 케이스(submit 채점용)
   * </pre>
   *
   * <code>repeated .problem.v1.IoPair hidden_cases = 13 [json_name = "hiddenCases"];</code>
   */
  com.cotejs.contracts.problem.v1.IoPairOrBuilder getHiddenCasesOrBuilder(
      int index);

  /**
   * <code>.problem.v1.ValidationReport validation = 14 [json_name = "validation"];</code>
   * @return Whether the validation field is set.
   */
  boolean hasValidation();
  /**
   * <code>.problem.v1.ValidationReport validation = 14 [json_name = "validation"];</code>
   * @return The validation.
   */
  com.cotejs.contracts.problem.v1.ValidationReport getValidation();
  /**
   * <code>.problem.v1.ValidationReport validation = 14 [json_name = "validation"];</code>
   */
  com.cotejs.contracts.problem.v1.ValidationReportOrBuilder getValidationOrBuilder();

  /**
   * <pre>
   * 파이프라인 자체가 실패한 경우(LLM 오류 등)의 구조화 표현. 정상 산출이면 비어 있다.
   * </pre>
   *
   * <code>.common.v1.Error failure = 15 [json_name = "failure"];</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <pre>
   * 파이프라인 자체가 실패한 경우(LLM 오류 등)의 구조화 표현. 정상 산출이면 비어 있다.
   * </pre>
   *
   * <code>.common.v1.Error failure = 15 [json_name = "failure"];</code>
   * @return The failure.
   */
  com.cotejs.contracts.common.v1.Error getFailure();
  /**
   * <pre>
   * 파이프라인 자체가 실패한 경우(LLM 오류 등)의 구조화 표현. 정상 산출이면 비어 있다.
   * </pre>
   *
   * <code>.common.v1.Error failure = 15 [json_name = "failure"];</code>
   */
  com.cotejs.contracts.common.v1.ErrorOrBuilder getFailureOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp generated_at = 16 [json_name = "generatedAt"];</code>
   * @return Whether the generatedAt field is set.
   */
  boolean hasGeneratedAt();
  /**
   * <code>.google.protobuf.Timestamp generated_at = 16 [json_name = "generatedAt"];</code>
   * @return The generatedAt.
   */
  com.google.protobuf.Timestamp getGeneratedAt();
  /**
   * <code>.google.protobuf.Timestamp generated_at = 16 [json_name = "generatedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getGeneratedAtOrBuilder();

  /**
   * <code>.common.v1.TraceContext trace = 17 [json_name = "trace"];</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.common.v1.TraceContext trace = 17 [json_name = "trace"];</code>
   * @return The trace.
   */
  com.cotejs.contracts.common.v1.TraceContext getTrace();
  /**
   * <code>.common.v1.TraceContext trace = 17 [json_name = "trace"];</code>
   */
  com.cotejs.contracts.common.v1.TraceContextOrBuilder getTraceOrBuilder();
}
