// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

/**
 * <pre>
 * 자동 검증 리포트 — 검수자(사람)가 "무엇이 얼마나 검증됐는지" 보고 판단하는 근거.
 * 검증 설계: N개 독립 풀이 합의 + brute-force 대조 + batch 실채점(engineering-notes '생성 문제 정답 신뢰성').
 * </pre>
 *
 * Protobuf type {@code problem.v1.ValidationReport}
 */
@com.google.protobuf.Generated
public final class ValidationReport extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:problem.v1.ValidationReport)
    ValidationReportOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ValidationReport");
  }
  // Use ValidationReport.newBuilder() to construct.
  private ValidationReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ValidationReport() {
    notes_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.problem.v1.ValidationReport.class, com.cotejs.contracts.problem.v1.ValidationReport.Builder.class);
  }

  public static final int SOLUTIONS_TOTAL_FIELD_NUMBER = 1;
  private int solutionsTotal_ = 0;
  /**
   * <pre>
   * 독립 생성한 풀이 수와 그중 출력이 합의에 도달한 수.
   * </pre>
   *
   * <code>uint32 solutions_total = 1 [json_name = "solutionsTotal"];</code>
   * @return The solutionsTotal.
   */
  @java.lang.Override
  public int getSolutionsTotal() {
    return solutionsTotal_;
  }

  public static final int SOLUTIONS_AGREED_FIELD_NUMBER = 2;
  private int solutionsAgreed_ = 0;
  /**
   * <code>uint32 solutions_agreed = 2 [json_name = "solutionsAgreed"];</code>
   * @return The solutionsAgreed.
   */
  @java.lang.Override
  public int getSolutionsAgreed() {
    return solutionsAgreed_;
  }

  public static final int BRUTE_FORCE_CHECKED_FIELD_NUMBER = 3;
  private boolean bruteForceChecked_ = false;
  /**
   * <pre>
   * brute-force 대조 수행 여부(작은 입력 출력 일치 + 큰 입력 TLE 변별 확인).
   * </pre>
   *
   * <code>bool brute_force_checked = 3 [json_name = "bruteForceChecked"];</code>
   * @return The bruteForceChecked.
   */
  @java.lang.Override
  public boolean getBruteForceChecked() {
    return bruteForceChecked_;
  }

  public static final int JUDGE_VERIFIED_FIELD_NUMBER = 4;
  private boolean judgeVerified_ = false;
  /**
   * <pre>
   * 대표 풀이가 judge(batch 레인) 실채점으로 전 케이스 통과했는지.
   * </pre>
   *
   * <code>bool judge_verified = 4 [json_name = "judgeVerified"];</code>
   * @return The judgeVerified.
   */
  @java.lang.Override
  public boolean getJudgeVerified() {
    return judgeVerified_;
  }

  public static final int NOTES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object notes_ = "";
  /**
   * <pre>
   * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
   * </pre>
   *
   * <code>string notes = 5 [json_name = "notes"];</code>
   * @return The notes.
   */
  @java.lang.Override
  public java.lang.String getNotes() {
    java.lang.Object ref = notes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notes_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
   * </pre>
   *
   * <code>string notes = 5 [json_name = "notes"];</code>
   * @return The bytes for notes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotesBytes() {
    java.lang.Object ref = notes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (solutionsTotal_ != 0) {
      output.writeUInt32(1, solutionsTotal_);
    }
    if (solutionsAgreed_ != 0) {
      output.writeUInt32(2, solutionsAgreed_);
    }
    if (bruteForceChecked_ != false) {
      output.writeBool(3, bruteForceChecked_);
    }
    if (judgeVerified_ != false) {
      output.writeBool(4, judgeVerified_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notes_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, notes_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (solutionsTotal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, solutionsTotal_);
    }
    if (solutionsAgreed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, solutionsAgreed_);
    }
    if (bruteForceChecked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, bruteForceChecked_);
    }
    if (judgeVerified_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, judgeVerified_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notes_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, notes_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.problem.v1.ValidationReport)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.problem.v1.ValidationReport other = (com.cotejs.contracts.problem.v1.ValidationReport) obj;

    if (getSolutionsTotal()
        != other.getSolutionsTotal()) return false;
    if (getSolutionsAgreed()
        != other.getSolutionsAgreed()) return false;
    if (getBruteForceChecked()
        != other.getBruteForceChecked()) return false;
    if (getJudgeVerified()
        != other.getJudgeVerified()) return false;
    if (!getNotes()
        .equals(other.getNotes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOLUTIONS_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getSolutionsTotal();
    hash = (37 * hash) + SOLUTIONS_AGREED_FIELD_NUMBER;
    hash = (53 * hash) + getSolutionsAgreed();
    hash = (37 * hash) + BRUTE_FORCE_CHECKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBruteForceChecked());
    hash = (37 * hash) + JUDGE_VERIFIED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getJudgeVerified());
    hash = (37 * hash) + NOTES_FIELD_NUMBER;
    hash = (53 * hash) + getNotes().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.problem.v1.ValidationReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.problem.v1.ValidationReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.problem.v1.ValidationReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.problem.v1.ValidationReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 자동 검증 리포트 — 검수자(사람)가 "무엇이 얼마나 검증됐는지" 보고 판단하는 근거.
   * 검증 설계: N개 독립 풀이 합의 + brute-force 대조 + batch 실채점(engineering-notes '생성 문제 정답 신뢰성').
   * </pre>
   *
   * Protobuf type {@code problem.v1.ValidationReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:problem.v1.ValidationReport)
      com.cotejs.contracts.problem.v1.ValidationReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.problem.v1.ValidationReport.class, com.cotejs.contracts.problem.v1.ValidationReport.Builder.class);
    }

    // Construct using com.cotejs.contracts.problem.v1.ValidationReport.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      solutionsTotal_ = 0;
      solutionsAgreed_ = 0;
      bruteForceChecked_ = false;
      judgeVerified_ = false;
      notes_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.problem.v1.Candidate.internal_static_problem_v1_ValidationReport_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.ValidationReport getDefaultInstanceForType() {
      return com.cotejs.contracts.problem.v1.ValidationReport.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.ValidationReport build() {
      com.cotejs.contracts.problem.v1.ValidationReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.problem.v1.ValidationReport buildPartial() {
      com.cotejs.contracts.problem.v1.ValidationReport result = new com.cotejs.contracts.problem.v1.ValidationReport(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.problem.v1.ValidationReport result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.solutionsTotal_ = solutionsTotal_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.solutionsAgreed_ = solutionsAgreed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bruteForceChecked_ = bruteForceChecked_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.judgeVerified_ = judgeVerified_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.notes_ = notes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.problem.v1.ValidationReport) {
        return mergeFrom((com.cotejs.contracts.problem.v1.ValidationReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.problem.v1.ValidationReport other) {
      if (other == com.cotejs.contracts.problem.v1.ValidationReport.getDefaultInstance()) return this;
      if (other.getSolutionsTotal() != 0) {
        setSolutionsTotal(other.getSolutionsTotal());
      }
      if (other.getSolutionsAgreed() != 0) {
        setSolutionsAgreed(other.getSolutionsAgreed());
      }
      if (other.getBruteForceChecked() != false) {
        setBruteForceChecked(other.getBruteForceChecked());
      }
      if (other.getJudgeVerified() != false) {
        setJudgeVerified(other.getJudgeVerified());
      }
      if (!other.getNotes().isEmpty()) {
        notes_ = other.notes_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              solutionsTotal_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              solutionsAgreed_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              bruteForceChecked_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              judgeVerified_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              notes_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int solutionsTotal_ ;
    /**
     * <pre>
     * 독립 생성한 풀이 수와 그중 출력이 합의에 도달한 수.
     * </pre>
     *
     * <code>uint32 solutions_total = 1 [json_name = "solutionsTotal"];</code>
     * @return The solutionsTotal.
     */
    @java.lang.Override
    public int getSolutionsTotal() {
      return solutionsTotal_;
    }
    /**
     * <pre>
     * 독립 생성한 풀이 수와 그중 출력이 합의에 도달한 수.
     * </pre>
     *
     * <code>uint32 solutions_total = 1 [json_name = "solutionsTotal"];</code>
     * @param value The solutionsTotal to set.
     * @return This builder for chaining.
     */
    public Builder setSolutionsTotal(int value) {

      solutionsTotal_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 독립 생성한 풀이 수와 그중 출력이 합의에 도달한 수.
     * </pre>
     *
     * <code>uint32 solutions_total = 1 [json_name = "solutionsTotal"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSolutionsTotal() {
      bitField0_ = (bitField0_ & ~0x00000001);
      solutionsTotal_ = 0;
      onChanged();
      return this;
    }

    private int solutionsAgreed_ ;
    /**
     * <code>uint32 solutions_agreed = 2 [json_name = "solutionsAgreed"];</code>
     * @return The solutionsAgreed.
     */
    @java.lang.Override
    public int getSolutionsAgreed() {
      return solutionsAgreed_;
    }
    /**
     * <code>uint32 solutions_agreed = 2 [json_name = "solutionsAgreed"];</code>
     * @param value The solutionsAgreed to set.
     * @return This builder for chaining.
     */
    public Builder setSolutionsAgreed(int value) {

      solutionsAgreed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 solutions_agreed = 2 [json_name = "solutionsAgreed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSolutionsAgreed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      solutionsAgreed_ = 0;
      onChanged();
      return this;
    }

    private boolean bruteForceChecked_ ;
    /**
     * <pre>
     * brute-force 대조 수행 여부(작은 입력 출력 일치 + 큰 입력 TLE 변별 확인).
     * </pre>
     *
     * <code>bool brute_force_checked = 3 [json_name = "bruteForceChecked"];</code>
     * @return The bruteForceChecked.
     */
    @java.lang.Override
    public boolean getBruteForceChecked() {
      return bruteForceChecked_;
    }
    /**
     * <pre>
     * brute-force 대조 수행 여부(작은 입력 출력 일치 + 큰 입력 TLE 변별 확인).
     * </pre>
     *
     * <code>bool brute_force_checked = 3 [json_name = "bruteForceChecked"];</code>
     * @param value The bruteForceChecked to set.
     * @return This builder for chaining.
     */
    public Builder setBruteForceChecked(boolean value) {

      bruteForceChecked_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * brute-force 대조 수행 여부(작은 입력 출력 일치 + 큰 입력 TLE 변별 확인).
     * </pre>
     *
     * <code>bool brute_force_checked = 3 [json_name = "bruteForceChecked"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBruteForceChecked() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bruteForceChecked_ = false;
      onChanged();
      return this;
    }

    private boolean judgeVerified_ ;
    /**
     * <pre>
     * 대표 풀이가 judge(batch 레인) 실채점으로 전 케이스 통과했는지.
     * </pre>
     *
     * <code>bool judge_verified = 4 [json_name = "judgeVerified"];</code>
     * @return The judgeVerified.
     */
    @java.lang.Override
    public boolean getJudgeVerified() {
      return judgeVerified_;
    }
    /**
     * <pre>
     * 대표 풀이가 judge(batch 레인) 실채점으로 전 케이스 통과했는지.
     * </pre>
     *
     * <code>bool judge_verified = 4 [json_name = "judgeVerified"];</code>
     * @param value The judgeVerified to set.
     * @return This builder for chaining.
     */
    public Builder setJudgeVerified(boolean value) {

      judgeVerified_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 대표 풀이가 judge(batch 레인) 실채점으로 전 케이스 통과했는지.
     * </pre>
     *
     * <code>bool judge_verified = 4 [json_name = "judgeVerified"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJudgeVerified() {
      bitField0_ = (bitField0_ & ~0x00000008);
      judgeVerified_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object notes_ = "";
    /**
     * <pre>
     * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
     * </pre>
     *
     * <code>string notes = 5 [json_name = "notes"];</code>
     * @return The notes.
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
     * </pre>
     *
     * <code>string notes = 5 [json_name = "notes"];</code>
     * @return The bytes for notes.
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
     * </pre>
     *
     * <code>string notes = 5 [json_name = "notes"];</code>
     * @param value The notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      notes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
     * </pre>
     *
     * <code>string notes = 5 [json_name = "notes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNotes() {
      notes_ = getDefaultInstance().getNotes();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
     * </pre>
     *
     * <code>string notes = 5 [json_name = "notes"];</code>
     * @param value The bytes for notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      notes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:problem.v1.ValidationReport)
  }

  // @@protoc_insertion_point(class_scope:problem.v1.ValidationReport)
  private static final com.cotejs.contracts.problem.v1.ValidationReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.problem.v1.ValidationReport();
  }

  public static com.cotejs.contracts.problem.v1.ValidationReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidationReport>
      PARSER = new com.google.protobuf.AbstractParser<ValidationReport>() {
    @java.lang.Override
    public ValidationReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValidationReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidationReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.problem.v1.ValidationReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

