// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: problem/v1/candidate.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.problem.v1;

@com.google.protobuf.Generated
public interface ValidationReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:problem.v1.ValidationReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 독립 생성한 풀이 수와 그중 출력이 합의에 도달한 수.
   * </pre>
   *
   * <code>uint32 solutions_total = 1 [json_name = "solutionsTotal"];</code>
   * @return The solutionsTotal.
   */
  int getSolutionsTotal();

  /**
   * <code>uint32 solutions_agreed = 2 [json_name = "solutionsAgreed"];</code>
   * @return The solutionsAgreed.
   */
  int getSolutionsAgreed();

  /**
   * <pre>
   * brute-force 대조 수행 여부(작은 입력 출력 일치 + 큰 입력 TLE 변별 확인).
   * </pre>
   *
   * <code>bool brute_force_checked = 3 [json_name = "bruteForceChecked"];</code>
   * @return The bruteForceChecked.
   */
  boolean getBruteForceChecked();

  /**
   * <pre>
   * 대표 풀이가 judge(batch 레인) 실채점으로 전 케이스 통과했는지.
   * </pre>
   *
   * <code>bool judge_verified = 4 [json_name = "judgeVerified"];</code>
   * @return The judgeVerified.
   */
  boolean getJudgeVerified();

  /**
   * <pre>
   * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
   * </pre>
   *
   * <code>string notes = 5 [json_name = "notes"];</code>
   * @return The notes.
   */
  java.lang.String getNotes();
  /**
   * <pre>
   * 사람 검수자를 위한 자유 서술(생성 모델·반려 사유·특이사항).
   * </pre>
   *
   * <code>string notes = 5 [json_name = "notes"];</code>
   * @return The bytes for notes.
   */
  com.google.protobuf.ByteString
      getNotesBytes();
}
