// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/error.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.common.v1;

@com.google.protobuf.Generated
public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
   * </pre>
   *
   * <code>string code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
   * </pre>
   *
   * <code>string code = 1 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
   * @return The enum numeric value on the wire for origin.
   */
  int getOriginValue();
  /**
   * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
   * @return The origin.
   */
  com.cotejs.contracts.common.v1.FaultOrigin getOrigin();

  /**
   * <pre>
   * **재시도해도 되는가.** 발신자만 알 수 있는 정보다 — 수신자의 추측에 맡기지 않는다.
   * </pre>
   *
   * <code>bool retryable = 4 [json_name = "retryable"];</code>
   * @return The retryable.
   */
  boolean getRetryable();

  /**
   * <pre>
   * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
   * </pre>
   *
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <pre>
   * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
   * </pre>
   *
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
