// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/error.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.common.v1;

@com.google.protobuf.Generated
public final class ErrorOuterClass extends com.google.protobuf.GeneratedFile {
  private ErrorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ErrorOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_v1_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_v1_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025common/v1/error.proto\022\tcommon.v1\"\233\001\n\005E" +
      "rror\022\022\n\004code\030\001 \001(\tR\004code\022\030\n\007message\030\002 \001(" +
      "\tR\007message\022.\n\006origin\030\003 \001(\0162\026.common.v1.F" +
      "aultOriginR\006origin\022\034\n\tretryable\030\004 \001(\010R\tr" +
      "etryable\022\026\n\006detail\030\005 \001(\tR\006detail*_\n\013Faul" +
      "tOrigin\022\034\n\030FAULT_ORIGIN_UNSPECIFIED\020\000\022\027\n" +
      "\023FAULT_ORIGIN_CALLER\020\001\022\031\n\025FAULT_ORIGIN_P" +
      "ROVIDER\020\002Bb\n\036com.cotejs.contracts.common" +
      ".v1P\001Z>github.com/rlatkd/cotejs/services" +
      "/judge/gen/common/v1;commonv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_v1_Error_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_common_v1_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_v1_Error_descriptor,
        new java.lang.String[] { "Code", "Message", "Origin", "Retryable", "Detail", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
