// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/error.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.common.v1;

/**
 * Protobuf type {@code common.v1.Error}
 */
@com.google.protobuf.Generated
public final class Error extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:common.v1.Error)
    ErrorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Error");
  }
  // Use Error.newBuilder() to construct.
  private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Error() {
    code_ = "";
    message_ = "";
    origin_ = 0;
    detail_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.common.v1.Error.class, com.cotejs.contracts.common.v1.Error.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
   * </pre>
   *
   * <code>string code = 1 [json_name = "code"];</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
   * </pre>
   *
   * <code>string code = 1 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <pre>
   * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
   * </pre>
   *
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGIN_FIELD_NUMBER = 3;
  private int origin_ = 0;
  /**
   * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
   * @return The enum numeric value on the wire for origin.
   */
  @java.lang.Override public int getOriginValue() {
    return origin_;
  }
  /**
   * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
   * @return The origin.
   */
  @java.lang.Override public com.cotejs.contracts.common.v1.FaultOrigin getOrigin() {
    com.cotejs.contracts.common.v1.FaultOrigin result = com.cotejs.contracts.common.v1.FaultOrigin.forNumber(origin_);
    return result == null ? com.cotejs.contracts.common.v1.FaultOrigin.UNRECOGNIZED : result;
  }

  public static final int RETRYABLE_FIELD_NUMBER = 4;
  private boolean retryable_ = false;
  /**
   * <pre>
   * **재시도해도 되는가.** 발신자만 알 수 있는 정보다 — 수신자의 추측에 맡기지 않는다.
   * </pre>
   *
   * <code>bool retryable = 4 [json_name = "retryable"];</code>
   * @return The retryable.
   */
  @java.lang.Override
  public boolean getRetryable() {
    return retryable_;
  }

  public static final int DETAIL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object detail_ = "";
  /**
   * <pre>
   * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
   * </pre>
   *
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The detail.
   */
  @java.lang.Override
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      detail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
   * </pre>
   *
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The bytes for detail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    if (origin_ != com.cotejs.contracts.common.v1.FaultOrigin.FAULT_ORIGIN_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, origin_);
    }
    if (retryable_ != false) {
      output.writeBool(4, retryable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(detail_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, detail_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    if (origin_ != com.cotejs.contracts.common.v1.FaultOrigin.FAULT_ORIGIN_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, origin_);
    }
    if (retryable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, retryable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(detail_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, detail_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.common.v1.Error)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.common.v1.Error other = (com.cotejs.contracts.common.v1.Error) obj;

    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (origin_ != other.origin_) return false;
    if (getRetryable()
        != other.getRetryable()) return false;
    if (!getDetail()
        .equals(other.getDetail())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
    hash = (53 * hash) + origin_;
    hash = (37 * hash) + RETRYABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetryable());
    hash = (37 * hash) + DETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getDetail().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.common.v1.Error parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.common.v1.Error parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.common.v1.Error parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.common.v1.Error parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.common.v1.Error prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.v1.Error}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.v1.Error)
      com.cotejs.contracts.common.v1.ErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.common.v1.Error.class, com.cotejs.contracts.common.v1.Error.Builder.class);
    }

    // Construct using com.cotejs.contracts.common.v1.Error.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = "";
      message_ = "";
      origin_ = 0;
      retryable_ = false;
      detail_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.common.v1.ErrorOuterClass.internal_static_common_v1_Error_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.Error getDefaultInstanceForType() {
      return com.cotejs.contracts.common.v1.Error.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.Error build() {
      com.cotejs.contracts.common.v1.Error result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.Error buildPartial() {
      com.cotejs.contracts.common.v1.Error result = new com.cotejs.contracts.common.v1.Error(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.common.v1.Error result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.origin_ = origin_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.retryable_ = retryable_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.detail_ = detail_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.common.v1.Error) {
        return mergeFrom((com.cotejs.contracts.common.v1.Error)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.common.v1.Error other) {
      if (other == com.cotejs.contracts.common.v1.Error.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.origin_ != 0) {
        setOriginValue(other.getOriginValue());
      }
      if (other.getRetryable() != false) {
        setRetryable(other.getRetryable());
      }
      if (!other.getDetail().isEmpty()) {
        detail_ = other.detail_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              origin_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              retryable_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              detail_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
     * </pre>
     *
     * <code>string code = 1 [json_name = "code"];</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
     * </pre>
     *
     * <code>string code = 1 [json_name = "code"];</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
     * </pre>
     *
     * <code>string code = 1 [json_name = "code"];</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
     * </pre>
     *
     * <code>string code = 1 [json_name = "code"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 기계가 분기하는 안정 식별자(예: "BUNDLE_HASH_MISMATCH"). 문구는 바뀌어도 이건 불변.
     * </pre>
     *
     * <code>string code = 1 [json_name = "code"];</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 사람이 읽는 설명. 분기 조건으로 쓰지 말 것.
     * </pre>
     *
     * <code>string message = 2 [json_name = "message"];</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int origin_ = 0;
    /**
     * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
     * @return The enum numeric value on the wire for origin.
     */
    @java.lang.Override public int getOriginValue() {
      return origin_;
    }
    /**
     * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
     * @param value The enum numeric value on the wire for origin to set.
     * @return This builder for chaining.
     */
    public Builder setOriginValue(int value) {
      origin_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
     * @return The origin.
     */
    @java.lang.Override
    public com.cotejs.contracts.common.v1.FaultOrigin getOrigin() {
      com.cotejs.contracts.common.v1.FaultOrigin result = com.cotejs.contracts.common.v1.FaultOrigin.forNumber(origin_);
      return result == null ? com.cotejs.contracts.common.v1.FaultOrigin.UNRECOGNIZED : result;
    }
    /**
     * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
     * @param value The origin to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setOrigin(com.cotejs.contracts.common.v1.FaultOrigin value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      origin_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.common.v1.FaultOrigin origin = 3 [json_name = "origin"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOrigin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      origin_ = 0;
      onChanged();
      return this;
    }

    private boolean retryable_ ;
    /**
     * <pre>
     * **재시도해도 되는가.** 발신자만 알 수 있는 정보다 — 수신자의 추측에 맡기지 않는다.
     * </pre>
     *
     * <code>bool retryable = 4 [json_name = "retryable"];</code>
     * @return The retryable.
     */
    @java.lang.Override
    public boolean getRetryable() {
      return retryable_;
    }
    /**
     * <pre>
     * **재시도해도 되는가.** 발신자만 알 수 있는 정보다 — 수신자의 추측에 맡기지 않는다.
     * </pre>
     *
     * <code>bool retryable = 4 [json_name = "retryable"];</code>
     * @param value The retryable to set.
     * @return This builder for chaining.
     */
    public Builder setRetryable(boolean value) {

      retryable_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * **재시도해도 되는가.** 발신자만 알 수 있는 정보다 — 수신자의 추측에 맡기지 않는다.
     * </pre>
     *
     * <code>bool retryable = 4 [json_name = "retryable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryable() {
      bitField0_ = (bitField0_ & ~0x00000008);
      retryable_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <pre>
     * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
     * </pre>
     *
     * <code>string detail = 5 [json_name = "detail"];</code>
     * @return The detail.
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
     * </pre>
     *
     * <code>string detail = 5 [json_name = "detail"];</code>
     * @return The bytes for detail.
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
     * </pre>
     *
     * <code>string detail = 5 [json_name = "detail"];</code>
     * @param value The detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      detail_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
     * </pre>
     *
     * <code>string detail = 5 [json_name = "detail"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDetail() {
      detail_ = getDefaultInstance().getDetail();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 진단 부속 정보(스택·컴파일 로그 등). 크기가 커질 수 있어 표시·저장 정책은 수신자 몫.
     * </pre>
     *
     * <code>string detail = 5 [json_name = "detail"];</code>
     * @param value The bytes for detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      detail_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:common.v1.Error)
  }

  // @@protoc_insertion_point(class_scope:common.v1.Error)
  private static final com.cotejs.contracts.common.v1.Error DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.common.v1.Error();
  }

  public static com.cotejs.contracts.common.v1.Error getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Error>
      PARSER = new com.google.protobuf.AbstractParser<Error>() {
    @java.lang.Override
    public Error parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Error> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Error> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.common.v1.Error getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

