// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/error.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.common.v1;

/**
 * <pre>
 * 실패의 귀속 — **누구의 잘못인가**. 처리 방식이 여기서 갈린다.
 * </pre>
 *
 * Protobuf enum {@code common.v1.FaultOrigin}
 */
@com.google.protobuf.Generated
public enum FaultOrigin
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FAULT_ORIGIN_UNSPECIFIED = 0;</code>
   */
  FAULT_ORIGIN_UNSPECIFIED(0),
  /**
   * <pre>
   * 요청자 귀책(잘못된 입력·규칙 위반). 재시도해도 같다 — 사용자에게 알린다.
   * </pre>
   *
   * <code>FAULT_ORIGIN_CALLER = 1;</code>
   */
  FAULT_ORIGIN_CALLER(1),
  /**
   * <pre>
   * 처리자 귀책(내부 오류·의존 장애). 사용자 코드는 멀쩡하다 — 운영자가 봐야 한다.
   * </pre>
   *
   * <code>FAULT_ORIGIN_PROVIDER = 2;</code>
   */
  FAULT_ORIGIN_PROVIDER(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "FaultOrigin");
  }
  /**
   * <code>FAULT_ORIGIN_UNSPECIFIED = 0;</code>
   */
  public static final int FAULT_ORIGIN_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * 요청자 귀책(잘못된 입력·규칙 위반). 재시도해도 같다 — 사용자에게 알린다.
   * </pre>
   *
   * <code>FAULT_ORIGIN_CALLER = 1;</code>
   */
  public static final int FAULT_ORIGIN_CALLER_VALUE = 1;
  /**
   * <pre>
   * 처리자 귀책(내부 오류·의존 장애). 사용자 코드는 멀쩡하다 — 운영자가 봐야 한다.
   * </pre>
   *
   * <code>FAULT_ORIGIN_PROVIDER = 2;</code>
   */
  public static final int FAULT_ORIGIN_PROVIDER_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FaultOrigin valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FaultOrigin forNumber(int value) {
    switch (value) {
      case 0: return FAULT_ORIGIN_UNSPECIFIED;
      case 1: return FAULT_ORIGIN_CALLER;
      case 2: return FAULT_ORIGIN_PROVIDER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FaultOrigin>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FaultOrigin> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FaultOrigin>() {
          public FaultOrigin findValueByNumber(int number) {
            return FaultOrigin.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cotejs.contracts.common.v1.ErrorOuterClass.getDescriptor().getEnumType(0);
  }

  private static final FaultOrigin[] VALUES = values();

  public static FaultOrigin valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FaultOrigin(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:common.v1.FaultOrigin)
}

