// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/trace.proto
// Protobuf Java Version: 4.33.1

package com.cotejs.contracts.common.v1;

@com.google.protobuf.Generated
public final class Trace extends com.google.protobuf.GeneratedFile {
  private Trace() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Trace");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_v1_TraceContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_v1_TraceContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025common/v1/trace.proto\022\tcommon.v1\"h\n\014Tr" +
      "aceContext\022\031\n\010trace_id\030\001 \001(\tR\007traceId\022\027\n" +
      "\007span_id\030\002 \001(\tR\006spanId\022$\n\016parent_span_id" +
      "\030\003 \001(\tR\014parentSpanIdBb\n\036com.cotejs.contr" +
      "acts.common.v1P\001Z>github.com/rlatkd/cote" +
      "js/services/judge/gen/common/v1;commonv1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_v1_TraceContext_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_common_v1_TraceContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_v1_TraceContext_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", "ParentSpanId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
