// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/trace.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.common.v1;

/**
 * <pre>
 * 한 요청 흐름 전체를 식별하는 컨텍스트. 모든 서비스 간 메시지가 이것을 실어 나른다.
 * </pre>
 *
 * Protobuf type {@code common.v1.TraceContext}
 */
@com.google.protobuf.Generated
public final class TraceContext extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:common.v1.TraceContext)
    TraceContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TraceContext");
  }
  // Use TraceContext.newBuilder() to construct.
  private TraceContext(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TraceContext() {
    traceId_ = "";
    spanId_ = "";
    parentSpanId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cotejs.contracts.common.v1.TraceContext.class, com.cotejs.contracts.common.v1.TraceContext.Builder.class);
  }

  public static final int TRACE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <pre>
   * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
   * </pre>
   *
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
   * </pre>
   *
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPAN_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object spanId_ = "";
  /**
   * <pre>
   * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
   * </pre>
   *
   * <code>string span_id = 2 [json_name = "spanId"];</code>
   * @return The spanId.
   */
  @java.lang.Override
  public java.lang.String getSpanId() {
    java.lang.Object ref = spanId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      spanId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
   * </pre>
   *
   * <code>string span_id = 2 [json_name = "spanId"];</code>
   * @return The bytes for spanId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpanIdBytes() {
    java.lang.Object ref = spanId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      spanId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_SPAN_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentSpanId_ = "";
  /**
   * <pre>
   * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
   * </pre>
   *
   * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The parentSpanId.
   */
  @java.lang.Override
  public java.lang.String getParentSpanId() {
    java.lang.Object ref = parentSpanId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentSpanId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
   * </pre>
   *
   * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The bytes for parentSpanId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentSpanIdBytes() {
    java.lang.Object ref = parentSpanId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentSpanId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(spanId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, spanId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentSpanId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, parentSpanId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(spanId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, spanId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentSpanId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, parentSpanId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cotejs.contracts.common.v1.TraceContext)) {
      return super.equals(obj);
    }
    com.cotejs.contracts.common.v1.TraceContext other = (com.cotejs.contracts.common.v1.TraceContext) obj;

    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getSpanId()
        .equals(other.getSpanId())) return false;
    if (!getParentSpanId()
        .equals(other.getParentSpanId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRACE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + SPAN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSpanId().hashCode();
    hash = (37 * hash) + PARENT_SPAN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParentSpanId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cotejs.contracts.common.v1.TraceContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cotejs.contracts.common.v1.TraceContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cotejs.contracts.common.v1.TraceContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cotejs.contracts.common.v1.TraceContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 한 요청 흐름 전체를 식별하는 컨텍스트. 모든 서비스 간 메시지가 이것을 실어 나른다.
   * </pre>
   *
   * Protobuf type {@code common.v1.TraceContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.v1.TraceContext)
      com.cotejs.contracts.common.v1.TraceContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cotejs.contracts.common.v1.TraceContext.class, com.cotejs.contracts.common.v1.TraceContext.Builder.class);
    }

    // Construct using com.cotejs.contracts.common.v1.TraceContext.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      traceId_ = "";
      spanId_ = "";
      parentSpanId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cotejs.contracts.common.v1.Trace.internal_static_common_v1_TraceContext_descriptor;
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.TraceContext getDefaultInstanceForType() {
      return com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.TraceContext build() {
      com.cotejs.contracts.common.v1.TraceContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cotejs.contracts.common.v1.TraceContext buildPartial() {
      com.cotejs.contracts.common.v1.TraceContext result = new com.cotejs.contracts.common.v1.TraceContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cotejs.contracts.common.v1.TraceContext result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.spanId_ = spanId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.parentSpanId_ = parentSpanId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cotejs.contracts.common.v1.TraceContext) {
        return mergeFrom((com.cotejs.contracts.common.v1.TraceContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cotejs.contracts.common.v1.TraceContext other) {
      if (other == com.cotejs.contracts.common.v1.TraceContext.getDefaultInstance()) return this;
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSpanId().isEmpty()) {
        spanId_ = other.spanId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getParentSpanId().isEmpty()) {
        parentSpanId_ = other.parentSpanId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              spanId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              parentSpanId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object traceId_ = "";
    /**
     * <pre>
     * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
     * </pre>
     *
     * <code>string trace_id = 1 [json_name = "traceId"];</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
     * </pre>
     *
     * <code>string trace_id = 1 [json_name = "traceId"];</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
     * </pre>
     *
     * <code>string trace_id = 1 [json_name = "traceId"];</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
     * </pre>
     *
     * <code>string trace_id = 1 [json_name = "traceId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
     * </pre>
     *
     * <code>string trace_id = 1 [json_name = "traceId"];</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object spanId_ = "";
    /**
     * <pre>
     * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
     * </pre>
     *
     * <code>string span_id = 2 [json_name = "spanId"];</code>
     * @return The spanId.
     */
    public java.lang.String getSpanId() {
      java.lang.Object ref = spanId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        spanId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
     * </pre>
     *
     * <code>string span_id = 2 [json_name = "spanId"];</code>
     * @return The bytes for spanId.
     */
    public com.google.protobuf.ByteString
        getSpanIdBytes() {
      java.lang.Object ref = spanId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        spanId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
     * </pre>
     *
     * <code>string span_id = 2 [json_name = "spanId"];</code>
     * @param value The spanId to set.
     * @return This builder for chaining.
     */
    public Builder setSpanId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      spanId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
     * </pre>
     *
     * <code>string span_id = 2 [json_name = "spanId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpanId() {
      spanId_ = getDefaultInstance().getSpanId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
     * </pre>
     *
     * <code>string span_id = 2 [json_name = "spanId"];</code>
     * @param value The bytes for spanId to set.
     * @return This builder for chaining.
     */
    public Builder setSpanIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      spanId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object parentSpanId_ = "";
    /**
     * <pre>
     * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
     * </pre>
     *
     * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
     * @return The parentSpanId.
     */
    public java.lang.String getParentSpanId() {
      java.lang.Object ref = parentSpanId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentSpanId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
     * </pre>
     *
     * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
     * @return The bytes for parentSpanId.
     */
    public com.google.protobuf.ByteString
        getParentSpanIdBytes() {
      java.lang.Object ref = parentSpanId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentSpanId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
     * </pre>
     *
     * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
     * @param value The parentSpanId to set.
     * @return This builder for chaining.
     */
    public Builder setParentSpanId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentSpanId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
     * </pre>
     *
     * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParentSpanId() {
      parentSpanId_ = getDefaultInstance().getParentSpanId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
     * </pre>
     *
     * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
     * @param value The bytes for parentSpanId to set.
     * @return This builder for chaining.
     */
    public Builder setParentSpanIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentSpanId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:common.v1.TraceContext)
  }

  // @@protoc_insertion_point(class_scope:common.v1.TraceContext)
  private static final com.cotejs.contracts.common.v1.TraceContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cotejs.contracts.common.v1.TraceContext();
  }

  public static com.cotejs.contracts.common.v1.TraceContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TraceContext>
      PARSER = new com.google.protobuf.AbstractParser<TraceContext>() {
    @java.lang.Override
    public TraceContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TraceContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TraceContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cotejs.contracts.common.v1.TraceContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

