// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/v1/trace.proto
// Protobuf Java Version: 4.35.1

package com.cotejs.contracts.common.v1;

@com.google.protobuf.Generated
public interface TraceContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.TraceContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
   * </pre>
   *
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * 흐름 전체의 id(16바이트 hex, 32자). 요청 진입점에서 한 번 생성되고 끝까지 불변.
   * </pre>
   *
   * <code>string trace_id = 1 [json_name = "traceId"];</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <pre>
   * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
   * </pre>
   *
   * <code>string span_id = 2 [json_name = "spanId"];</code>
   * @return The spanId.
   */
  java.lang.String getSpanId();
  /**
   * <pre>
   * 이 메시지를 만든 구간의 id(8바이트 hex, 16자). 서비스마다 새로 만든다.
   * </pre>
   *
   * <code>string span_id = 2 [json_name = "spanId"];</code>
   * @return The bytes for spanId.
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();

  /**
   * <pre>
   * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
   * </pre>
   *
   * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The parentSpanId.
   */
  java.lang.String getParentSpanId();
  /**
   * <pre>
   * 이 구간을 만들어낸 상위 구간. 비어 있으면 흐름의 시작점.
   * </pre>
   *
   * <code>string parent_span_id = 3 [json_name = "parentSpanId"];</code>
   * @return The bytes for parentSpanId.
   */
  com.google.protobuf.ByteString
      getParentSpanIdBytes();
}
