# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: judge/v1/submission.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'judge/v1/submission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from common.v1 import trace_pb2 as common_dot_v1_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19judge/v1/submission.proto\x12\x08judge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15\x63ommon/v1/trace.proto\"\x9d\x03\n\nSubmission\x12#\n\rsubmission_id\x18\x01 \x01(\x03R\x0csubmissionId\x12\x1d\n\nproblem_id\x18\x02 \x01(\x03R\tproblemId\x12\x1a\n\x08language\x18\x03 \x01(\tR\x08language\x12\x1f\n\x0bsource_code\x18\x04 \x01(\tR\nsourceCode\x12\"\n\rtime_limit_ms\x18\x05 \x01(\rR\x0btimeLimitMs\x12&\n\x0fmemory_limit_mb\x18\x06 \x01(\rR\rmemoryLimitMb\x12&\n\x0ftest_bundle_key\x18\x07 \x01(\tR\rtestBundleKey\x12,\n\x12test_bundle_sha256\x18\x08 \x01(\tR\x10testBundleSha256\x12=\n\x0csubmitted_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bsubmittedAt\x12-\n\x05trace\x18\n \x01(\x0b\x32\x17.common.v1.TraceContextR\x05traceB_\n\x1d\x63om.cotejs.contracts.judge.v1P\x01Z<github.com/rlatkd/cotejs/services/judge/gen/judge/v1;judgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'judge.v1.submission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.cotejs.contracts.judge.v1P\001Z<github.com/rlatkd/cotejs/services/judge/gen/judge/v1;judgev1'
  _globals['_SUBMISSION']._serialized_start=96
  _globals['_SUBMISSION']._serialized_end=509
# @@protoc_insertion_point(module_scope)
